### ISSUE TITLE
[1.14.4] Server crash when right clicking double high corn - sidedness issue?

### ISSUE THREAD

**Issue by ProsperCraft** [enemeez/simplefarming#10]
Crash
https://gist.github.com/ProsperCraft/4b14f31b7796a4fd0540cbe23fd59ec9

forge-1.14.4-28.0.49
simplefarming-1.14.4-1.0.9

**Comment by Shadows-of-Fire** [comment]
Forge issue: https://github.com/MinecraftForge/MinecraftForge/issues/6024

**Comment by enemeez** [comment]
Already knew about this – releasing a hotfix soon

**Comment by enemeez** [comment]
Had to hardcode values, but this should be fixed for now
