### ISSUE TITLE
Recipes from the mod

### ISSUE THREAD

**Issue by Eisar93** [enemeez/simplefarming#100]
**Forge Version**
32.0.106
**Mod list (optional)**

**Log file (optional)**

**Describe the issue**
 Some recipes from the mod don't work. Kenaf fiber to string and most crops not converting into their seeds.

**Comment by cweckerl** [comment]
I'm testing this on 32.0.107, and it seems to work fine for me. A startup .log file might help me solve this

**Comment by Eisar93** [comment]
[2020-08-07-3.log.gz](https://github.com/cweckerl/simplefarming/files/5048199/2020-08-07-3.log.gz)

Here.

**Comment by Eisar93** [comment]
With most recent versions of Forge this problem seems to be resolved.
