### ISSUE TITLE
Block-type squashes/cantaloupe dropping instead of individual pieces

### ISSUE THREAD

**Issue by feckyeslife** [enemeez/simplefarming#110]
**Forge Version**
Forge 31.2.36

**Mod list (optional)**
[Valhelsia 2 pack](https://www.curseforge.com/minecraft/modpacks/valhelsia-2) version 2.2.10

**Log file (optional)**
No log file

**Describe the issue**
When harvesting the squash and cantaloupe crops, the block version is being dropped which then has to be manually re-placed in the world and re-broken to get the usable (eg. edible/craftable) versions of squash and cantaloupe. This happens whether I right click harvest or left click breaking the plant to harvest. 

I would think the expected behavior would be to get the individual pieces on harvesting and then manually recraft into the whole block as desired (like vanilla Melons). I wouldn't mind if there was a way to get the individual slices through the crafting bench or whatever, but having to manually place and re-break each squash and cantaloupe is annoying.

**Comment by cweckerl** [comment]
I've changed this so you can craft a gourd block (squash, cantaloupe, honeydew) into a guaranteed 5 individual slices.
