### ISSUE TITLE
Crash with lastest version at startup

### ISSUE THREAD

**Issue by traveldesign** [enemeez/simplefarming#112]
Hi, I've attached the crash reports for two crashes. One with Forge 34.1.25 and the other with Forge 34.1.39. Same thing happened each time. Crashes before getting to the main Minecraft screen.
[crash-2020-11-01_17.59.13-fml.txt](https://github.com/cweckerl/simplefarming/files/5472083/crash-2020-11-01_17.59.13-fml.txt)
[crash-2020-11-01_18.04.00-fml.txt](https://github.com/cweckerl/simplefarming/files/5472084/crash-2020-11-01_18.04.00-fml.txt)

**Comment by cweckerl** [comment]
I believe this is because I built the mod with an outdated Forge version. I will update to the latest version and release a new file
