### ISSUE TITLE
Lang pt_br

### ISSUE THREAD

**Issue by clustermage** [enemeez/simplefarming#119]
{
"itemGroup.simplefarming":"Agricultura Simples",
"block.simplefarming.cantaloupe_block":"Cantalupo",
"block.simplefarming.honeydew_block":"Melão",
"block.simplefarming.squash_block":"Abóbora",
"block.simplefarming.blackberry_bush":"Arbusto de Amora",
"block.simplefarming.blueberry_bush":"Arbusto de Mirtilo",
"block.simplefarming.raspberry_bush":"Arbusto de Framboesa",
"block.simplefarming.strawberry_bush":"Arbusto de Morango",
"block.simplefarming.oat_hay_block":"Fardo de Aveia",
"block.simplefarming.rye_hay_block":"Fardo de Centeio",
"block.simplefarming.rice_hay_block":"Fardo de Arroz",
"block.simplefarming.cantaloupe_crop":"Cultivo de Cantalupo",
"block.simplefarming.cassava_crop":"Cultivo de Mandioca",
"block.simplefarming.corn_crop":"Cultivo de Milho",
"block.simplefarming.cucumber_crop":"Cultivo de Pepino",
"block.simplefarming.eggplant_crop":"Cultivo de Berinjela",
"block.simplefarming.honeydew_crop":"Cultivo de Melão",
"block.simplefarming.ginger_crop":"Cultivo de Gengibre",
"block.simplefarming.kenaf_crop":"Cultivo de Kenaf",
"block.simplefarming.lettuce_crop":"Cultivo de Alface",
"block.simplefarming.oat_crop":"Cultivo de Aveia",
"block.simplefarming.onion_crop":"Cultivo de Cebola",
"block.simplefarming.peanut_crop":"Cultivo de Amendoim",
"block.simplefarming.pepper_crop":"Cultivo de Pimenta",
"block.simplefarming.radish_crop":"Cultivo de Rabanete",
"block.simplefarming.rice_crop":"Cultivo de Arroz",
"block.simplefarming.rye_crop":"Cultivo de Centeio",
"block.simplefarming.sorghum_crop":"Cultivo de Sorgo",
"block.simplefarming.soybean_crop":"Cultivo de Soja",
"block.simplefarming.squash_crop":"Cultivo de Abóbora",
"block.simplefarming.spinach_crop":"Cultivo de Espinafre",
"block.simplefarming.tomato_crop":"Cultivo de Tomate",
"block.simplefarming.wild_crop":"Cultivo Selvagem",
"block.simplefarming.yam_crop":"Cultivo de Inhame",
"block.simplefarming.grape_plant":"Cultivo de Uva",
"block.simplefarming.grape_block":"Uvas",
"block.simplefarming.grape_leaves":"Folhas de Uva",
"block.simplefarming.carrot_crop":"Cultivo de Cenoura",
"block.simplefarming.potato_crop":"Cultivo de Batata",
"item.simplefarming.cantaloupe_seeds":"Sementes de Cantalupo",
"item.simplefarming.carrot_seeds":"Sementes de Cenoura",
"item.simplefarming.cassava_seeds":"Sementes de Mandioca",
"item.simplefarming.corn_seeds":"Sementes de Milho",
"item.simplefarming.cucumber_seeds":"Sementes de Pepino",
"item.simplefarming.eggplant_seeds":"Sementes de Berinjela",
"item.simplefarming.honeydew_seeds":"Sementes de Melão",
"item.simplefarming.ginger_seeds":"Sementes de Gengibre",
"item.simplefarming.grape_seeds":"Sementes de Uva",
"item.simplefarming.kenaf_seeds":"Sementes de Kenaf",
"item.simplefarming.lettuce_seeds":"Sementes de Alface",
"item.simplefarming.oat_seeds":"Sementes de Aveia",
"item.simplefarming.onion_seeds":"Sementes de Cebola",
"item.simplefarming.peanut_seeds":"Sementes de Amendoim",
"item.simplefarming.pepper_seeds":"Sementes de Pimenta",
"item.simplefarming.potato_seeds":"Sementes de Batata",
"item.simplefarming.radish_seeds":"Sementes de Rabanete",
"item.simplefarming.rice_seeds":"Sementes de Arroz",
"item.simplefarming.rye_seeds":"Sementes de Centeio",
"item.simplefarming.sorghum_seeds":"Sementes de Sorgo",
"item.simplefarming.squash_seeds":"Sementes de Abóbora",
"item.simplefarming.soybean_seeds":"Sementes de Soja",
"item.simplefarming.spinach_seeds":"Sementes de Espinafre",
"item.simplefarming.tomato_seeds":"Sementes de Tomate",
"item.simplefarming.yam_seeds":"Sementes de Inhame",
"item.simplefarming.cumin_seeds":"Sementes de Cominho",
"item.simplefarming.quinoa_seeds":"Sementes de Quinoa",
"item.simplefarming.curry_powder":"Pó de Curry",
"item.simplefarming.apricot":"Damasco",
"item.simplefarming.banana":"Bananas",
"item.simplefarming.cherries":"Cerejas",
"item.simplefarming.grapes":"Uvas",
"item.simplefarming.mango":"Manga",
"item.simplefarming.orange":"Laranja",
"item.simplefarming.pear":"Pera",
"item.simplefarming.plum":"Ameixa",
"item.simplefarming.blackberries":"Amora Silvestre",
"item.simplefarming.blueberries":"Amoras",
"item.simplefarming.cactus_fruit":"Fruta do Cacto",
"item.simplefarming.cantaloupe":"Cantalupo",
"item.simplefarming.honeydew":"Melão",
"item.simplefarming.raspberries":"Framboesas",
"item.simplefarming.strawberries":"Morangos",
"item.simplefarming.cassava":"Mandioca",
"item.simplefarming.corn":"Milho",
"item.simplefarming.cucumber":"Pepino",
"item.simplefarming.eggplant":"Berinjela",
"item.simplefarming.habanero":"Habanero",
"item.simplefarming.ginger":"Gengibre",
"item.simplefarming.lettuce":"Alface",
"item.simplefarming.oat":"Aveia",
"item.simplefarming.onion":"Cebola",
"item.simplefarming.peanut":"Amendoim",
"item.simplefarming.pepper":"Pimenta",
"item.simplefarming.radish":"Rabanete",
"item.simplefarming.rice":"Arroz",
"item.simplefarming.rye":"Centeio",
"item.simplefarming.sorghum":"Sorgo",
"item.simplefarming.soybean":"Soja",
"item.simplefarming.spinach":"Espinafre",
"item.simplefarming.squash":"Abóbora",
"item.simplefarming.tomato":"Tomate",
"item.simplefarming.yam":"Inhame",
"item.simplefarming.kenaf_fiber":"Fibra de Kenaf",
"item.simplefarming.vinegar":"Vinagre",
"item.simplefarming.noodles":"Macarrão Noodles",
"block.simplefarming.apple_leaves":"Folhas de Maçã",
"block.simplefarming.apricot_leaves":"Folhas de Damasco",
"block.simplefarming.banana_leaves":"Folhas de Banana",
"block.simplefarming.cherry_leaves":"Folhas de Cereja",
"block.simplefarming.mango_leaves":"Folhas de Manga",
"block.simplefarming.orange_leaves":"Folhas de Laranja",
"block.simplefarming.pear_leaves":"Folhas de Pera",
"block.simplefarming.plum_leaves":"Folhas de Ameixa",
"block.simplefarming.apple_sapling":"Muda de Morango",
"block.simplefarming.apricot_sapling":"Muda de Damasco",
"block.simplefarming.banana_sapling":"Muda de Banana",
"block.simplefarming.cherry_sapling":"Muda de Cereja",
"block.simplefarming.mango_sapling":"Muda de Manga",
"block.simplefarming.orange_sapling":"Muda de Laranja",
"block.simplefarming.pear_sapling":"Muda de Pera",
"block.simplefarming.plum_sapling":"Muda de Ameixa",
"block.simplefarming.fruit_log":"Corte de Frutas",
"block.simplefarming.fruit_planks":"Tábuas de Frutas",
"block.simplefarming.chocolate_cake":"Bolo de Chocolate",
"block.simplefarming.cheese_block":"Peça de Queijo",
"block.simplefarming.cactus_crop":"Opuntia",
"item.simplefarming.apple_pie":"Torta de Maçã",
"item.simplefarming.apricot_pie":"Torta de Damasco",
"item.simplefarming.blackberry_pie":"Torta de Amora",
"item.simplefarming.blueberry_pie":"Torta de Mirtilo",
"item.simplefarming.cherry_pie":"Torta de Cereja",
"item.simplefarming.peanut_butter_pie":"Torta De Manteiga De Amendoim",
"item.simplefarming.pear_pie":"Torta de Pera",
"item.simplefarming.plum_pie":"Torta de Ameixa",
"item.simplefarming.raspberry_pie":"Torta de Framboesa",
"item.simplefarming.strawberry_pie":"Torta de Morango",
"item.simplefarming.baked_yam":"Inhame Assado",
"item.simplefarming.banana_bread":"Pão de Banana",
"item.simplefarming.blt":"BLT",
"item.simplefarming.caesar_salad":"Salada César",
"item.simplefarming.cassava_cake":"Bolo De Mandioca",
"item.simplefarming.cheese_slice":"Fatia de Queijo",
"item.simplefarming.cheeseburger":"Cheeseburger",
"item.simplefarming.chicken_parmesan":"Frango Parmesão",
"item.simplefarming.chili":"Chili",
"item.simplefarming.chocolate":"Chocolate",
"item.simplefarming.cooked_bacon":"Bacon Cozido",
"item.simplefarming.cooked_chicken_wings":"Asas De Frango Cozidas",
"item.simplefarming.cooked_sausage":"Linguiça Cozida",
"item.simplefarming.cooked_egg":"Ovo Cozido",
"item.simplefarming.cornbread":"Pão de Milho",
"item.simplefarming.corn_salad":"Salada de Milho",
"item.simplefarming.cucumber_soup":"Sopa de Pepino",
"item.simplefarming.egg_sandwich":"Sanduíche de Ovo",
"item.simplefarming.eggplant_parmesan":"Berinjela Parmesão",
"item.simplefarming.fish_fillet":"Filé de Peixe",
"item.simplefarming.fish_sandwich":"Sanduíche de Peixe",
"item.simplefarming.fried_calamari":"Calamari Frito",
"item.simplefarming.fruit_salad":"Salada de Frutas",
"item.simplefarming.golden_habanero":"Habanero Dourado",
"item.simplefarming.hamburger":"Hambúrger",
"item.simplefarming.hotdog":"Cachorro Quente",
"item.simplefarming.italian_beef":"Bife Italiano",
"item.simplefarming.jaffa_cake":"Bolo de Jaffa",
"item.simplefarming.lasagna":"Lasanha",
"item.simplefarming.mac_and_cheese":"Mac e Queijo",
"item.simplefarming.oatmeal":"Mingau de Aveia",
"item.simplefarming.onion_soup":"Sopa de Cebola",
"item.simplefarming.pancakes":"Panquecas",
"item.simplefarming.pasta":"Macarrão",
"item.simplefarming.pbj":"PB&J",
"item.simplefarming.peanut_butter_cookie":"Biscoito de Manteiga de Amendoim",
"item.simplefarming.pickle":"Picles",
"item.simplefarming.pickled_beetroot":"Beterraba em Conserva",
"item.simplefarming.pizza":"Pizza",
"item.simplefarming.popcorn":"Pipoca",
"item.simplefarming.pulled_pork_sandwich":"Sanduíche de Carne de Porco Desfiada",
"item.simplefarming.radish_soup":"Sopa de Rabanete",
"item.simplefarming.raw_bacon":"Bacon Cru",
"item.simplefarming.raw_calamari":"Calamari Cru",
"item.simplefarming.raw_chicken_wings":"Asas De Frango Cru",
"item.simplefarming.raw_sausage":"Linguiça Crua",
"item.simplefarming.rice_bowl":"Tigela de Arroz",
"item.simplefarming.salad":"Salada",
"item.simplefarming.sandwich":"Sanduiche",
"item.simplefarming.sorghum_bread":"Pão De Sorgo",
"item.simplefarming.sorghum_porridge":"Mingau de Sorgo",
"item.simplefarming.spaghetti":"Espaguete",
"item.simplefarming.spinach_mushroom_quiche":"Quiche de Cogumelo De Espinafre",
"item.simplefarming.squash_casserole":"Caçarola de Abóbora",
"item.simplefarming.sushi":"Sushi",
"item.simplefarming.tofu":"Tofu",
"item.simplefarming.tomato_soup":"Sopa de Tomate",
"item.simplefarming.vegetable_medley":"Mistura de Vegetais",
"item.simplefarming.oat_bread":"Pão de Aveia",
"item.simplefarming.rice_bread":"Pão de Arroz",
"item.simplefarming.rye_bread":"Pão de Centeio",
"item.simplefarming.raisins":"Passas de Uva",
"item.simplefarming.spinach_quinoa_quiche":"Quiche de Espinafre Quinoa",
"item.simplefarming.chicken_noodle_soup":"Sopa de Macarrão de frango",
"item.simplefarming.squash_soup":"Sopa de Abóbora",
"item.simplefarming.quinoa_salad":"Salada de Quinoa",
"item.simplefarming.tofu_scramble":"Tofu Scramble",
"item.simplefarming.beef_curry":"Curry de Carne",
"item.simplefarming.chicken_curry":"Curry de Frango",
"item.simplefarming.mutton_curry":"Curry de Carneiro",
"item.simplefarming.pork_curry":"Curry de Porco",
"item.simplefarming.vegetable_curry":"Curry de Vegetais",
"block.simplefarming.pea_crop":"Cultivo de Ervilha",
"block.simplefarming.cotton_crop":"Cultivo de Algodão",
"block.simplefarming.sweet_potato_crop":"Cultivo de Batata Doce",
"block.simplefarming.barley_crop":"Cultivo de Cevada",
"block.simplefarming.sunflower":"Girassol",
"block.simplefarming.cumin":"Cominho",
"block.simplefarming.quinoa":"Quinoa",
"item.simplefarming.pea_pod":"Vagem de Ervilha",
"item.simplefarming.pea_seeds":"Sementes de Ervilha",
"item.simplefarming.sweet_potato":"Batata Doce",
"item.simplefarming.sweet_potato_seeds":"Sementes de Batata Doce",
"item.simplefarming.barley":"Cevada",
"item.simplefarming.barley_seeds":"Sementes de Cevada",
"item.simplefarming.sunflower_seeds":"Sementes de Girassol",
"item.simplefarming.cotton":"Algodão",
"item.simplefarming.cotton_seeds":"Sementes de Algodão",
"item.simplefarming.baked_sweet_potato":"Batata Doce Assada",
"item.simplefarming.carrot_soup":"Sopa de Cenoura",
"item.simplefarming.pumpkin_soup":"Sopa de Abóbora",
"item.simplefarming.raw_horse_meat":"Carne de Cavalo Crua",
"item.simplefarming.cooked_horse_meat":"Carne de Cavalo Cozida",
"item.simplefarming.trail_mix":"Mistura de Trilha",
"item.simplefarming.sweet_potato_quinoa_cakes":"Bolo De Batata Doce Quinoa",
"item.simplefarming.sausage_barley_soup":"Sopa de Linguiça com Cevada",
"block.simplefarming.barley_hay_block":"Fardo de Cevada",
"item.simplefarming.barley_bread":"Pão de Cevada",
"item.simplefarming.pea_soup":"Sopa de Ervilha",
"item.simplefarming.fried_rice":"Arroz Frito",
"item.simplefarming.mushroom_barley":"Cevada de Cogumelo",
"item.simplefarming.olives":"Azeitonas",
"item.simplefarming.broccoli":"Brócolis",
"item.simplefarming.zucchini":"Abobrinha",
"item.simplefarming.olive_oil":"Azeite",
"item.simplefarming.broccoli_seeds":"Sementes de Brócolis",
"item.simplefarming.zucchini_seeds":"Sementes de Abobrinha",
"item.simplefarming.beef_and_broccoli":"Carne e Brócolis",
"item.simplefarming.broccoli_cheese_soup":"Sopa de Brócolis com Queijo",
"item.simplefarming.olive_tomato_salad":"Salada de Tomate com Azeitona",
"item.simplefarming.stuffed_corn_zucchini":"Abobrinha Recheada",
"item.simplefarming.zucchini_bread":"Pão de Abobrinha",
"block.simplefarming.olive_sapling":"Azeitona Verde",
"block.simplefarming.birthday_cake":"Bolo de Aniversário",
"block.simplefarming.broccoli_crop":"Cultivo de Brócolis",
"block.simplefarming.zucchini_crop":"Cultivo de Abobrinha",
"block.simplefarming.olive_leaves":"Folhas de Oliveira",
"block.simplefarming.scarecrow":"Espantalho",
"block.simplefarming.brewing_barrel":"Barril de Preparo",
"item.simplefarming.beer":"Cerveja",
"item.simplefarming.cider":"Cidra",
"item.simplefarming.wine":"Vinho",
"item.simplefarming.vodka":"Vodka",
"item.simplefarming.whiskey":"Uísque",
"item.simplefarming.tiswin":"Cachaça de Milho",
"item.simplefarming.cauim":"Cauim",
"item.simplefarming.sake":"Sake",
"item.simplefarming.borscht":"Borscht",
"item.simplefarming.candy":"Doce",
"item.simplefarming.jam":"Geléia",
"item.simplefarming.turnip":"Nabo",
"item.simplefarming.turnip_seeds":"Sementes de Nabo",
"item.simplefarming.chicory_root":"Raiz de Chicória",
"item.simplefarming.marshmallow_root":"Raiz de Marshmallow",
"item.simplefarming.candy_cane":"Bastão de Açucar",
"item.simplefarming.chicory_gratin":"Chicória Gratinado",
"item.simplefarming.fish_and_chips":"Peixe e Frita",
"item.simplefarming.ice_cream_sundae":"Sundae de Sorvete",
"item.simplefarming.marshmallow":"Marshmallow",
"item.simplefarming.pad_thai":"Pad Thai",
"item.simplefarming.potato_knish":"Knish de Batata",
"item.simplefarming.squid_ink_pasta":"Massa de Tinta de Lula",
"item.simplefarming.turnip_beetroot_gratin":"Nabo Beterraba Gratinado",
"block.simplefarming.turnip_crop":"Cultivo de Nabo",
"block.simplefarming.marshmallow":"Marshmallow",
"block.simplefarming.chicory":"Chicória",
"block.simplefarming.grape_leaves_base":"Folhas de Uva",
"item.simplefarming.sprinkles":"Balinhas",
"advancements.simplefarming.root.description":"Muitos alimentos para escolher!",
"advancements.simplefarming.berries.title":"Bons Frutos!",
"advancements.simplefarming.berries.description":"Colete todas as variantes de frutos silvestres",
"advancements.simplefarming.birthday_cake.title":"Para Alguém Especial",
"advancements.simplefarming.birthday_cake.description":"Faça um bolo de aniversário para comemorar!",
"advancements.simplefarming.cheese.title":"Direto da Fazenda",
"advancements.simplefarming.cheese.description":"Faça uma peça de queijo usando vinagre",
"advancements.simplefarming.cheeseburger.title":"Big Kahuna Burger",
"advancements.simplefarming.cheeseburger.description":"Coma um farto cheeseburger",
"advancements.simplefarming.crops.title":"Creme da Colheita",
"advancements.simplefarming.crops.description":"Cultive e colha cada colheita comestível",
"advancements.simplefarming.grapes.title":"Frutos Botanicamente",
"advancements.simplefarming.grapes.description":"Cultive e colha uvas de um vinhedo",
"advancements.simplefarming.scarecrow.title":"Melhor Amigo do Fazendeiro",
"advancements.simplefarming.scarecrow.description":"Faça um espantalho para evitar que suas plantações sejam pisoteadas!",
"advancements.simplefarming.wine.title":"Encher a Cara",
"advancements.simplefarming.wine.description":"Faça uma garrafa de vinho usando uvas no barril de fermentação",
"item.simplefarming.mead":"Hidromel",
"item.simplefarming.music_disc_nourish":"Disco de Música",
"item.simplefarming.music_disc_nourish.desc":"Bearfan - Nourish",
"item.simplefarming.veggie_burger":"Hambúrguer Vegetariano"
}

**Comment by cweckerl** [comment]
Just added. Thank you!
