### ISSUE TITLE
Texture Glitch

### ISSUE THREAD

**Issue by Sam7524** [enemeez/simplefarming#121]
**Forge Version**
1.16.1
**Mod list (optional)**

**Log file (optional)**

**Describe the issue**
When I plant crops the textures are different than what they are supposed to be so there's no way for me to know when the crops are done growing. Corn for example grows as a sunflower with a bush on top of it and the carrots grow as honeydews. Every crop is not what it is supposed to be. When I try to harvest them they only drop the seed and no finished crop. The bushes work fine, it is just the crops for some reason. I don't know if this is an issue on my end or not.

**Comment by cweckerl** [comment]
Unfortunately, that's just how the mod is.

You can get what stage of growth the crop is in by pressing F3 and looking at the block state properties. Other mods like HWYLA or the one probe can also tell you the growth stage.
