### ISSUE TITLE
Cheese Automatisation

### ISSUE THREAD

**Issue by sirati** [enemeez/simplefarming#125]
**Forge Version**
1.15
**Describe the issue**
At the current state its impossible to automate cheese wheel to cheese slice. This should be possible

**Comment by BobVarioa** [comment]
I would also like to add that automating right clicks with another mod (i.e. Click Machine) works until the last 3 slices. (I'm not really sure if this is a Click Machine issue but it doesn't seem to be.)

**Comment by sirati** [comment]
this should be an issue with click machine.
simulating right clicking with a create machine works fine


edit: I think i know why you have this problem. click machine does not click the block in front of it, instead it sends a ray trace from the centre of the block and clicks the block the ray trace hits. so when the cheese gets slim enough it misses it. just move clickmachine over 90 degrees
