### ISSUE TITLE
silent gear lumberaxe & fruittrees

### ISSUE THREAD

**Issue by Bucky420** [enemeez/simplefarming#127]
forge-1.15.2-31.2.46.jar

Valhelsia 2

[crash-2020-12-20_16.41.44-server.txt](https://github.com/cweckerl/simplefarming/files/5721231/crash-2020-12-20_16.41.44-server.txt)

just simply chpping down trees with a lumber axe (chops hole tree)  from slient gear and whent back to my base and then came back to the server frozen / crashed with a new crash report. 

my best guess is ither its calling code on a tree that no longer exists or was part of the clean up when items get removed as there were a few items on the ground like fruts and stuff i my self was next to a chest in my base nothing directily tiggert it it was a timed event. posably the lumber axe has compatiblity issues with this mod and how it removed the blocks

this could also be an issue with a entity walking over it no clue it has pathfinding stuff in the crashlog.

**Comment by Elenterius** [comment]
@codydbgt you mixed up your fruit trees. This is crash is not related to simplefarming. Please report the crash to the fruittrees & performant mod authors.

**Comment by Bucky420** [comment]
ic there seprate mods ty for the info :/
