### ISSUE TITLE
List of hunger + sat values for food?

### ISSUE THREAD

**Issue by TheK0ntr0ller** [enemeez/simplefarming#140]
I'd really like to know the best food items hunger value + saturation wise. Also, which plants need water and which don't?

Thanks so much, absolutely love the mod.

**Comment by cweckerl** [comment]
The mod [AppleSkin](https://www.curseforge.com/minecraft/mc-mods/appleskin) will help with this.

If you need more information, read through [this](https://github.com/cweckerl/simplefarming/blob/1.16/src/main/java/enemeez/simplefarming/integration/FoodTier.java).
