### ISSUE TITLE
Did i do something wrong?

### ISSUE THREAD

**Issue by Crystal8c** [enemeez/simplefarming#144]
Hi,
uhm sorry if this is not very professional but ye  i have a problem with dragging it into the field where you can see your rescours pack, mods and stuff
well if im dragging it in it wont show up so its like i ant use it.

**Comment by koalalord9999** [comment]
I'm not entirely sure what you're asking. If you're asking how to install the mod, you open your instance of minecraft with a correctly running Forge. Go to the mods folder, and drag and drop the .zip provided through here, or CurseForge.
