### ISSUE TITLE
Error loading mod when running with OpenJ9

### ISSUE THREAD

**Issue by markusxu** [enemeez/simplefarming#149]
**Forge Version**
35.1.37

**Log file & Mod list (optional)**
[crash-2021-02-10_12.50.59-fml.txt](https://github.com/cweckerl/simplefarming/files/5955923/crash-2021-02-10_12.50.59-fml.txt)

**Describe the issue**
Error loading mod when running with OpenJ9

**Comment by ghost** [comment]
Exact same issue here. Running OpenJ9 on Windows 10 x64 with forge 36.0.42

**Comment by Greyneon** [comment]
crashes on Forge version 36.0.40 aswell with openJDK

[crash-2021-03-06_14.41.29-fml.txt](https://github.com/cweckerl/simplefarming/files/6095411/crash-2021-03-06_14.41.29-fml.txt)

**Comment by caseyjfer** [comment]
Seeing the same issue. Forge 36.1.0 server and client

**Comment by markusxu** [comment]
The issue has been fixed by eclipse/openj9#12148 and eclipse/openj9#12164.
The first nightly build which applied the fix is https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/tag/jdk8u-2021-03-11-08-45.
