### ISSUE TITLE
Config won't work

### ISSUE THREAD

**Issue by ivanovic77** [enemeez/simplefarming#152]
**Forge Version**
**1.16.4-Forge-35.1.37**

**Mod Version:**
**simplefarming-1.16.4-1.3.5.jar**

There are many options in the configuration file that don't work. "Generate wild drops" on "true" doesn't disable grass drops as intended. Chances of wild crops, wild plants and berry bushes generating in the overworld are ignored when you increase or decrease the number.

Note: I'm using Biomes O' Plenty.

**Comment by NielsPilgaard** [comment]
I'm seeing the same behaviour, the config and serverconfig don't appear to change anything.
