### ISSUE TITLE
Farmer's Delight Compability

### ISSUE THREAD

**Issue by chief-turkler** [enemeez/simplefarming#157]
I'm a user of both Simple Farming and Farmer's Delight, they seem to work together without issues except for some overlap.

![2021-03-23_20 15 42](https://user-images.githubusercontent.com/49252967/112198287-03777500-8c1e-11eb-84b9-f549fea3cc5b.png)
![2021-03-23_20 15 44](https://user-images.githubusercontent.com/49252967/112198296-05413880-8c1e-11eb-9ff1-078a9fd0b127.png)

Things like tomatoes seem to have some overlap. Would it be possible for a compability patch to be made?

**Comment by RobMarsh1201** [comment]
One thing I noticed was that fermenting barrel's wont accept rice from farmers delight. Maybe make thing check for forge dictionaries instead of item ID's?
