### ISSUE TITLE
Disable dropout from grass

### ISSUE THREAD

**Issue by r0sso** [enemeez/simplefarming#158]
Hey! How to disable seed dropout from vanilla and other grass?

**Comment by MokahTGS** [comment]
Also allow turning off seed drops from harvesting crops.  We are swimming in seeds.

**Comment by r0sso** [comment]
there is no disabling of drop seed in the config, exists only for harvesting. is it possible to disable drop of mod seeds from vanilla grass by destroying it with left click?
