### ISSUE TITLE
LOTR Dim

### ISSUE THREAD

**Issue by EmmaRavens** [enemeez/simplefarming#164]
Good evening, not sure if this a Simple Farming issue, but when I added "lotr:middle_earth" it still keeps spawning bushes in the dimension and what happens is what you can see in the screenshot

Forge 36.1.24
Simple Farming 1.3.6
The Lord of the Rings Renewed 4.1

```
#Correct format -> "mod_id:dimension"
        black_dim = ["minecraft:nether", "minecraft:end", "lotr:middle_earth"]
```

![SP](https://user-images.githubusercontent.com/12566399/120556662-b6213c00-c3f4-11eb-9781-452f151bb334.png)

**Comment by cweckerl** [comment]
Thanks.

I discovered this earlier and have a fix ready.

**Comment by EmmaRavens** [comment]
Thank you a lot, hopefully that will fix it
