### ISSUE TITLE
Nausea's Comeback

### ISSUE THREAD

**Issue by Erysch** [enemeez/simplefarming#168]
Some people of mine would love to see a comeback of the nausea effect from the brewing items.
Was there a special reason that it has been removed?

Greetings (=
Nice mod though!!

**Comment by cweckerl** [comment]
I'll add it back as a config option

**Comment by Erysch** [comment]
Wow, that sounds perfect. Thank you! (:

**Comment by JoeA42** [comment]
That would be awesome!
