### ISSUE TITLE
Tooltips for Serene Seasons

### ISSUE THREAD

**Issue by wharris912** [enemeez/simplefarming#177]
This mod is compatible with Serene Seasons, but Simple Farming plants and seeds do not have tooltips. However, the vanilla plants and BOB plants have tooltips under the name of the plant that tells you what season(s) they are fertile. For example, wheat is fertile in the summer and autumn, but tomatoes and apples are fertile when?). Can this be added to the mod to reduce confusion if you are playing with seasons?

**Comment by cweckerl** [comment]
Will be addressed in next build
