### ISSUE TITLE
Scarecrow does not protect against crops being trampled

### ISSUE THREAD

**Issue by Amcplayer1** [enemeez/simplefarming#179]
Unfortunately, the scarecrow doesn't protect any of my crops from being trampled, it is on an even flat surface, and no blocks, at any radius, (even blocks directly surrounding the scarecrow) are protected when jumped or landed on.  (I am using simple farming 1.19.3 2.0.2 download from curse forge)

**Comment by cweckerl** [comment]
https://github.com/cweckerl/simplefarming/commit/f315763d63791751431264deabe8941576ebbfc3

Will be addressed in next build
