### ISSUE TITLE
Grapes simply aren’t working for me

### ISSUE THREAD

**Issue by idkAdam666** [enemeez/simplefarming#180]
Forge 44.1.17 
Minecraft 1.19.3

Followed the tutorial on your mod page and on the wiki here, for whatever reason I can’t plant grapes in dirt, I have to till the land with a hoe first and once the grape bush appears it never yields any grapes and I am putting fences down. Not sure if any of my mods are conflicting or if I’m dumb and missing a step, I’m fairly new to modding.

Here are my mods: 

- Moonlight Library
- Xaero’s Minimap + World Map
- JRFTL (Just Another Rotten Flesh To Leather)
- JEI

All of these are up to date. I tried going into a creative world to test the grapes on a very high tick rate and still nothing.

**Comment by cweckerl** [comment]
Sorry, docs are not updated. In newer versions, you attach the `trellis` block to the grape plant's top part. Then leaves will spread and grapevine will growth below.
