### ISSUE TITLE
Grape tree not working

### ISSUE THREAD

**Issue by kisielewskka** [enemeez/simplefarming#184]
I used the fence metod but somehowe the tree isn't growing.  I planted them a while ago but it just looks like this. Is it my fault or is there an issue with the mod?
![2023-04-01_22 57 04](https://user-images.githubusercontent.com/129626680/229313668-d0ecbd48-6cdf-43ee-9e1b-c13fdfa3628d.png)

**Comment by Inkquill256** [comment]
I think you have to use the Trellis item instead of the fences now

**Comment by MariesaMist** [comment]
You need to use the trellis
