### ISSUE TITLE
Minecraft 1.20, growing grapes is not possible

### ISSUE THREAD

**Issue by Kkleszczu** [enemeez/simplefarming#187]
Hey, so I'm wondering how to grow grapes? I was trying to use Trellis but no matter what combination of placing them near / above/ next to grapes the only thing that is happening is that they are growing fully until they were suppose to grow leaves, then they are breaking. How am I suppose to grow them? It doesnt matter if im using only Simple Farming mod or any other mods, they just don't want to work. Video of problem is included.

https://github.com/cweckerl/simplefarming/assets/137715875/d132092b-6651-4659-870e-7e13568b8d2f

**Comment by cweckerl** [comment]
https://www.youtube.com/watch?v=_H-vnFMk26g

You need to leave one space above open :smile:

**Comment by Kkleszczu** [comment]
Okay, fine, but as you can see on my vid the grapes doesn't grow to leaves state. They just destroys themselves even without anything above them
