### ISSUE TITLE
[1.14.4] Request to add forge tag for quinoa

### ISSUE THREAD

**Issue by kwpugh** [enemeez/simplefarming#19]
Hi,

Would you consider adding a forge tag called "quinoa" that points to your quinoa_seeds so I can leverage them in a recipe in my mod?

Thank you for considering.

Regards.

**Comment by kwpugh** [comment]
Actually, to be more generalized.  Could you create a forge tag called "proteins" and include plant items high in protein such as soybean, peanut, and quinoa?   I use a proteins tag in my recipe to make protein powder from vanilla eggs and my own quinoa.   I don't include proteins that come from meats and fish, just plant-based proteins.  My mod is about high nutrition foods without killing animals.

Thank you for considering.

**Comment by enemeez** [comment]
Thanks for reminding me. The next update will have a more comprehensive forge tag system with each food getting their own tag. I'll add the protein tag as well.

**Comment by kwpugh** [comment]
Thank you.  Really nice modding work by the way.

**Comment by kwpugh** [comment]
Thanks.
