### ISSUE TITLE
Cant brew with Fermenter

### ISSUE THREAD

**Issue by AshxDragon** [enemeez/simplefarming#192]
Hi, i'm not able to brew anything with the Fermenter Block, maybe something i'am missing?
Put an ingridient in the upper Box and an empty bottle in the lower, nothing happens... In the wiki theres just the old brewing Barrel and no information for the Fermenter.

Using the 19.2 Version (2.0.4)

**Comment by cweckerl** [comment]
How long are you waiting? Process will take some time

**Comment by AshxDragon** [comment]
hi, i did wait a few ingame days, but figured out now that i took the wrong ingridient for first (honey for mead instead of the comb) and the animation for some reason dont apply for me, but for my wife it does, she can see the process starting with the "filling" Arrow. Thanks a lot for your response
