### ISSUE TITLE
[1.14.4] REQUEST: a few more forge tags please

### ISSUE THREAD

**Issue by kwpugh** [enemeez/simplefarming#24]
Hi,

I know I have asked a bunch, but could I request one more?

Two new tags to be specifically: carbs and vegetables

Carbs:
- barley
- oat
- rye
- sorghum

Vegetables:
- broccoli
- eggplant
- lettuce
- onion
- pea_pod
- pepper
- radish
- zucchini

Thank you .

Kind regards.

**Comment by enemeez** [comment]
@kwpugh Do you want just these items specifically? I can just add all types of vegetables/carbs if you want.

**Comment by kwpugh** [comment]
Hi,

Those would be fine.

Regards.
