### ISSUE TITLE
Allow Fruit Logs to be Waterlogged

### ISSUE THREAD

**Issue by WenXin20** [enemeez/simplefarming#30]
Fruit Logs is a nice decoration block, but when placed in water, it replaces the water instead of becoming waterlogged. This would be a nice feature to have if possible.

**Comment by enemeez** [comment]
![2019-10-19_16 38 59](https://user-images.githubusercontent.com/52186431/67151117-10f13880-f28f-11e9-978a-b5cf1d4a943e.png)

**Comment by enemeez** [comment]
Will be released in next update
