### ISSUE TITLE
[1.14.4-1.21] right click  harvesting not working

### ISSUE THREAD

**Issue by kreezxil** [enemeez/simplefarming#33]
I had a right click harvesting mod installed but removed it because your mod is supposed to allow that. I have the following config set

```toml
["Miscellaneous Features"]
        #Indicates whether right-click harvesting crops should be enabled
        "Enable right-click harvesting for crops" = true
        #Smart harvesting allows right-click harvested items to be placed directly in the player's inventory. Enabling this option will automatically disable normal right-click harvesting. Indicat$
        "Enable smart harvest for crops" = false
        #Chance of seeds dropping from breaking grass (Default: 6.25 (6.25%))
        #Range: 0.0 ~ 100.0
        "Percent chance of seeds dropping" = 6.25
```

Players are now asking to install a right click harvesting mod. Does this mean there is something wrong with your mod? or did I not understand your config?

mod version: 1.14.4-1.21

**Comment by enemeez** [comment]
The config seems to be set up correctly. Simple Farming has been tested on 1.14 modpack servers as well, so I don't think it would be a server-side issue. Would you be able to provide me a modlist assuming you are using multiple mods?

**Comment by kreezxil** [comment]
you can look in my **Minecolonies Getting Started** pack for 1.14.4. There
are not that many mods in it. On a side note I would say it is you because
I switched your mod for Reap Mod on my new 1.14.4 pack called **Better Than
Minecolonies Getting Started** and the right click harvesting began working
again.

It might be that I update to the latest FORGE constantly. both packs are
28.1.60 now and will be on 28.1.61 tonite.

**Comment by enemeez** [comment]
Testing in a single player world in the Minecolonies Getting Started pack, the right click harvesting seems to function correctly. Unfortunately, I will need more information to fix any potential issues

**Comment by fowltief** [comment]
running into the same issue on Enemiga pack 4 v0.3.7  multiplayer server.  Simple Farm 1.14.4-1.25 right-click the barrel with a glass bottle and nothing. doesn't drop or show any error code.

**Comment by enemeez** [comment]
Thanks for reporting it. I'll have it fixed in the next update.
