### ISSUE TITLE
Compatibility with Cooking for Blockheads

### ISSUE THREAD

**Issue by InspectorCaracal** [enemeez/simplefarming#39]
I'm really enjoying this mod so far, but I also like to use [Cooking for Blockheads](https://www.curseforge.com/minecraft/mc-mods/cooking-for-blockheads) for my recipe-management needs when making food, and while all of the end result foods show up fine in the recipe book, the intermediate ingredients like noodles don't.

I know that back in 1.12 with Harvestcraft, CfB picks up fine on recipes for inedible intermediate ingredients like butter and dough, but I'm not sure what the difference is between those and e.g. the noodles in this mod.

If you could try to figure out how to make that work, I would be _super_ grateful. If not, thank you for your hard work on making the mod anyway!

**Comment by enemeez** [comment]
Thanks for bringing this up. I'll definitely see what I can do

**Comment by enemeez** [comment]
A pull request was merged with Cooking for Blockheads to increase compatibility with simple farming. So the next update released for CfB should have automatic compatibility with my mod.

**Comment by InspectorCaracal** [comment]
Thanks so much!!
