### ISSUE TITLE
Corn

### ISSUE THREAD

**Issue by heygillianm** [enemeez/simplefarming#41]
**Forge Version**
28.1.0

**Mod list (optional)**
Simple Farming
TorchMaster
Mr.Crays Furniture Mod
**Log file (optional)**

**Describe the issue**
This is the only crop this is happening to, but everytime I try to harvest corn, I only get seeds. I try bonemeal and it tells me it's 100% grown, but I can't harvest any actual corn.

**Comment by enemeez** [comment]
Unfortunately, I tested this out myself and cannot reproduce the same issue.

The corn crop is designed to grow two blocks high, so perhaps you may be trying to harvest only the lower part of the crop. Another suggestion is to let the crop grow naturally without bonemeal as the bonemeal is quite glitchy with advancing its age.
