### ISSUE TITLE
Strategy for 1.14 forge tags

### ISSUE THREAD

**Issue by Draradech** [enemeez/simplefarming#42]
I'm opening an identical issue for  XL-Food-Mod and simplefarming.

Please get into contact with each other and coordinate on forge tags for food items. Currently your tags are going into different directions (forge:tomato vs. forge:fruits/tomato and forge:protein/corn vs. forge:vegetables/(raw_)corn), which will cause confusion ("Why can't I use this tomato in that recipe?").

As far as I can tell your mods are the biggest food mods for 1.14 right now. If you can agree on a unified strategy, it might just set a de facto standard for food item tags for 1.14 and beyond. 

XL Food mod issue: https://github.com/mariot7/XL-Food-Mod/issues/40

**Comment by enemeez** [comment]
Thanks for bring this up. I actually properly fixed the tags a couple of weeks ago, but I haven't had enough time to push out an update. You can see them in the data folder in the repository.

From what I see in Forge, the correct way of tagging should be forge:crops/name
