### ISSUE TITLE
Crash on Joining World

### ISSUE THREAD

**Issue by NillerMedDild** [enemeez/simplefarming#44]
**Forge Version**
1.14.4-28.1.103
**Mod list (optional)**

**Log file (optional)**
https://gist.github.com/NillerMedDild/6d90ab82b6fed0aad484c26729b7a695

**Describe the issue**
Updating to SimpleFarming 1.2.4 results in a crash when joining a single player world. 

The crash report doesn't point towards SimpleFarming, but the issue is resolved by downgrading to Simple Farming 1.2.2.

**Comment by enemeez** [comment]
This looks like an odd interaction between simple farming and cooking for blockheads. I'll see what I can do.

**Comment by enemeez** [comment]
After narrowing it down to a few mods, I think this crash is caused by craft tweaker, cooking for blockheads, and simple farming. I'm not too familiar with craft tweaker for 1.14, but are you using any scripts to add/change recipes with any of the simple farming or cfb blocks?

**Comment by NillerMedDild** [comment]
D'oh, yes I do have one recipe that involves Simple Farming:
```
Output: <item:simplefarming:cornbread>
Inputs, Shapeless:  [<tag:simplefarming:grain>, <tag:forge:corn>, <tag:simplefarming:grain>]
```

Could the use of `<tag:simplefarming:grain>` be the culprit?

**Comment by enemeez** [comment]
Yes! That tag was removed in the recent update and moved to forge:grain or forge:crops/wheat

**Comment by NillerMedDild** [comment]
Ahh, I had no idea wrong tags could cause so much damage, thanks for your help!
