### ISSUE TITLE
Grass not dropping seeds in the new update

### ISSUE THREAD

**Issue by doubleaxes** [enemeez/simplefarming#46]
**Forge Version**
1.14.4 28.1.74
**Mod list (optional)**

**Log file (optional)**
[http://www.mediafire.com/file/fjwqrmd1gmqcqtx/latest.log/file](url)
**Describe the issue**
when I punch grass it is not dropping like the older version it drops so rarely

**Comment by enemeez** [comment]
Seeds were intentionally given a lower drop rate to stop filling up inventories so quickly. I believe there are over 30 seeds that can drop, so I didn't want it to get too overwhelming for players.

I will consider raising it a small bit or potentially giving a config option for it.

**Comment by doubleaxes** [comment]
> Seeds were intentionally given a lower drop rate to stop filling up inventories so quickly. I believe there are over 30 seeds that can drop, so I didn't want it to get too overwhelming for players.
> 
> I will consider raising it a small bit or potentially giving a config option for it.

oh okay then thanks for the answer
