### ISSUE TITLE
Compatibility for Watering Cans with right-click harvest

### ISSUE THREAD

**Issue by NillerMedDild** [enemeez/simplefarming#47]
Hello!

I use Simple Farming's right-click harvest functionality in my modpack, and it makes it impossible to use Watering Cans (from the Watercan mod) while looking at crops, grown or not, even while holding sneak.
It would be nice if the right-click harvest would only "fire" if the crop is ready to be harvested, allowing usage of held items.

I asked the developer of Watercan to see if he could fix this initially, but he was unable to find a way to do it from his side.

Original issue: https://github.com/codetaylor/watercan/issues/16

**Comment by enemeez** [comment]
By readjusting one line of code I was able to pretty easily fix this. Thank you for reporting. It will be fixed in the next update.

**Comment by NillerMedDild** [comment]
Thanks!
