### ISSUE TITLE
Alcohol disappears when harvested sometimes.

### ISSUE THREAD

**Issue by beanpoleahead** [enemeez/simplefarming#48]
**Forge Version**
28.1.107
**Mod list (optional)**
![modlist](https://user-images.githubusercontent.com/59546126/71790151-20f5fa00-2fec-11ea-953a-3f9db3461095.png)
**Log file (optional)**

**Describe the issue**
Sometimes, when collecting alcohol from barrels, the bottle, with the alcohol in it, will disappear. Nothing I'm doing seems to affect when the bottle disappears. I've dug around the barrel with no luck. I've watched the alcohol to see when it finishes brewing to harvest as soon as possible, and I've waited a long time after it finishes to harvest, and it still seems to be random. The following is a list of how many times I've tried to harvest alcohol (the number to the right), and how many times I've succeeded (the number to the left).
Beer 2/5, Cauim 1/2, Cider 1/2, Sake 2/3, Tiswin 1/1, Vodka 1/2, Whiskey 2/3, Wine 3/4.

**Comment by enemeez** [comment]
Thank you for reporting. This will be fixed in the next updates for 1.14 and 1.15.
