### ISSUE TITLE
[1.14.4] ENHANCEMENT - Adding fruits tab to forge

### ISSUE THREAD

**Issue by kwpugh** [enemeez/simplefarming#5]
Hi,

Would you consider adding a tag to Forge, maybe called "fruits", to tag all of the various fruits in your mod?

My mod is intended to use fruits + a drying agent to create fructose powder.  This would allow my mod to work with your fruit.

Thank you for considering.

Regards.

**Comment by enemeez** [comment]
Definitely will do this and update the rest of my Forge tags

**Comment by kwpugh** [comment]
Thank you.
