### ISSUE TITLE
Unidentified mapping after update from 1.2.5 to 1.2.6

### ISSUE THREAD

**Issue by Z0rdak** [enemeez/simplefarming#53]
**Forge Version**
28.1.109

**Mod list (optional)**
No other mods are related in this issue.

**Log file (optional)**
-

**Describe the issue**
I updated the mods of my server yesterday an after the startup i've got this error:

> [07:26:03] [Server thread/ERROR] [ne.mi.re.GameData/REGISTRIES]: Unidentified mapping from registry minecraft:item
>         simplefarming:sprinkles: 1572
> 
> [07:26:03] [Server thread/WARN] [ne.mi.fm.StartupQuery/STARTUPQUERY]: Forge Mod Loader detected missing registry entries.
> 
> There are 1 missing entries in this save.
> If you continue the missing entries will get removed.
> A world backup will be automatically created in your saves directory.
> 
> Missing minecraft:item:
>     simplefarming:sprinkles

I know this can happen, as stated in the log:

> [07:26:03] [Server thread/WARN] [ne.mi.fm.FMLWorldPersistenceHook/WP]: This world was saved with mod simplefarming version **1.14.4-1.2.5** and it is now at version **1.14.4-1.2.6**, things may not work well

Just want to check if this is an oversight or intentional.

**Comment by enemeez** [comment]
This is an error on my part. Transferring computers has caused some of the old and new files to get mixed up. This caused the sprinkles to become unregistered as an item.

Thanks for reporting this. I'll have it fixed in the next update.
