### ISSUE TITLE
1.15.2 latest mod crash

### ISSUE THREAD

**Issue by WeiEAL** [enemeez/simplefarming#59]
Crash after destroying fruit tree leaves
Only keep this mod to start the game destroying the leaves will not crash
[crash-2020-02-06_22.57.29-server.txt](https://github.com/enemeez/simplefarming/files/4165714/crash-2020-02-06_22.57.29-server.txt)

**Comment by WeiEAL** [comment]
I have tested and found that there is a bug between FastLeafDecay and SimpleFarming

**Comment by MinQinxy** [comment]
I have the same problem with you. It just crashed when I destroy the leaves of  fruit tree.
