### ISSUE TITLE
Berry bushes and fruit trees eat torches?

### ISSUE THREAD

**Issue by Cr4fTJuNkiE** [enemeez/simplefarming#6]
When I right click on a berry bush or fruit tree leaf block with a torch in hand it disappears? It makes the torch placement sound, but just eats it.. lol

**Comment by enemeez** [comment]
The torches actually are not consumed. This is just a client-side bug, and if you click on the torches in your inventory you should have the same amount.

**Comment by Cr4fTJuNkiE** [comment]
Hmmm... Could swore they missing. Thanks.

**Comment by enemeez** [comment]
This is now fixed with the new right-clicking mechanic
