### ISSUE TITLE
Question about fruit tree spaws

### ISSUE THREAD

**Issue by MaximeDawn** [enemeez/simplefarming#61]
Hi, so i'm playing with the latest version of the mod (1.2.6 on Minecraft 1.14.4) and I never saw a fruit tree yet.
Do they still spawn if you add the mod AFTER the map was generated ? I get berry bushed correctly tho

**Comment by enemeez** [comment]
If you added the mod after creating the world, you will have to load new world chunks for fruit trees to spawn.
