### ISSUE TITLE
Kenaf isn't dropping fibers from mature plants

### ISSUE THREAD

**Issue by InspectorCaracal** [enemeez/simplefarming#62]
**Forge Version**
1.14.4-forge-28.1.90

**Mod list (optional)**
AppleSkin, AutoRegLib, Clumps, colouredchat, CookingForBlockheads, Hwyla, Quark, simplefarming, Xaero's Minimap, Xaero's World Map

**Describe the issue**
On a small private server I'm running, harvesting (or even breaking) a mature kenaf plant doesn't drop any fibers. Except for one specific plant, so far, we're only getting back one seed if we break the plant, and nothing if we harvest it.

**Comment by enemeez** [comment]
Thanks for reporting this. Are you sure you are waiting until the kenaf is two blocks high? Otherwise this is an issue I will look into.

**Comment by InspectorCaracal** [comment]
We did but they weren't growing any higher, although the two new kenaf plants that I planted after posting this _did_ grow to two blocks like they were supposed to, so I'm starting to be suspicious it was a weird server glitch...

I'll post more information if it happens again, or if it seems to have stopped happening I'll come back and close it as probably an issue elsewhere.
