### ISSUE TITLE
Conflict with Fast leaf decay causes exception

### ISSUE THREAD

**Issue by Lordbaane** [enemeez/simplefarming#63]
---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 2/15/20 4:50 PM
Description: Exception in server tick loop

java.lang.ClassCastException: enemeez.simplefarming.blocks.growable.FruitLeavesBlock cannot be cast to net.minecraft.block.LeavesBlock
	at net.olafkeijsers.fastleafdecay.FldScheduler.tick(FldScheduler.java:55) ~[?:v20] {re:classloading}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:212) ~[eventbus-2.0.0-milestone.1-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:204) ~[eventbus-2.0.0-milestone.1-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-2.0.0-milestone.1-service.jar:?] {}
	at net.minecraftforge.fml.hooks.BasicEventHooks.onPostServerTick(BasicEventHooks.java:119) ~[?:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:823) ~[?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,pl:mixin:APP:assets/immersive_portals/immersive_portals.mixins.json:MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:635) [?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,pl:mixin:APP:assets/immersive_portals/immersive_portals.mixins.json:MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: FreeBSD (amd64) version 11.2-STABLE
	Java Version: 1.8.0_232, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3402277800 bytes (3244 MB) / 4510973952 bytes (4302 MB) up to 7635730432 bytes (7282 MB)
	CPUs: 24
	JVM Flags: 2 total; -Xmx8192M -Xms2048M
	ModLauncher: 5.0.0-milestone.4+67+b1a340b
	ModLauncher launch target: fmlserver
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-2.0.0-milestone.1-service.jar eventbus PLUGINSERVICE 
		/forge-1.15.2-31.1.1.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.15.2-31.1.1.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.0.0-milestone.1-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.15.2-31.1.1.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.15.2-31.1.1.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.15.2-31.1.1.jar fml TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.1.jar mixinbootstrap TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.1.jar mixin PLUGINSERVICE 
		/MixinBootstrap-1.0.1.jar mixinbootstrap PLUGINSERVICE 
	FML: 31.1
	Forge: net.minecraftforge:31.1.1
	FML Language Providers: 
		javafml@31.1
		minecraft@1
	Mod List: 
		NetherPortalFix_1.15.2-6.0.0.jar NetherPortalFix {netherportalfix@6.0.0 DONE}
		rhodonite-1.15.2-1.0.0.jar Rhodonite {rhodonite@1.15.2-1.0.0 DONE}
		prefab-1.5.0.0.jar Prefab {prefab@1.5.0.0 DONE}
		EditSign-1.15.2-2.0.0+7.jar Edit Sign {edit_sign@2.0.0+7 DONE}
		bambooeverything-1.15-1.0.0.jar Bamboo Everything {bambooeverything@1.15-1.0.0 DONE}
		BowInfinityFix-1.15.2-rv8.jar Bow Infinity Fix {bowinfinityfix@rv8 DONE}
		XaerosWorldMap_1.5.5_Forge_1.15.2.jar Xaero's World Map {xaeroworldmap@1.5.5 DONE}
		JRFTL+[1.15.2]-1.1.jar JRFTL {jrftl@1.1 DONE}
		Placebo-1.15.2-3.0.2.jar Placebo {placebo@3.0.2 DONE}
		essentialfeatures-3.1.0.jar Essential Features {essentialfeatures@3.1.0 DONE}
		potionsmaster-0.0.8-1.15.2-31.0.1.jar Potions Master {potionsmaster@0.0.8 DONE}
		WitherSkeletonTweaks-1.15.1-4.0.0.jar Wither Skeleton Tweaks {wstweaks@4.0.0 DONE}
		guardvillagers-1.15.2-1.0.1.jar Guard Villagers {guardvillagers@1.0.1 DONE}
		u_team_core-1.15.2-2.10.4.153.jar U Team Core {uteamcore@2.10.4.153 DONE}
		Hwyla-forge-1.10.8-B72_1.15.2.jar Waila {waila@version DONE}
		SnowRealMagic-1.15.2-1.7.2.jar Snow! Real Magic! {snowrealmagic@1.7.2 DONE}
		carpetstairsmod-mc1.5-v1.1.jar Carpet Stairs Mod {carpetstairsmod@1.1 DONE}
		corpse-1.15.2-1.0.2.jar Corpse {corpse@1.15.2-1.0.2 DONE}
		mcw-bridges-1.0.3-mc1.15.2.jar Macaw's Bridges {mcwbridges@1.0.3 DONE}
		lightestlampsmod-3.3.0.jar Lightest Lamps {lightestlamp@3.3.0 DONE}
		useful_backpacks-1.15.2-1.9.3.62.jar Useful Backpacks {usefulbackpacks@1.9.3.62 DONE}
		valhelsia_structures-1.15.1-0.0.1.jar Valhelsia Structures {valhelsia_structures@1.15.1-0.0.1 DONE}
		ironfurnaces-1.15.2-1.9.0.jar Iron Furnaces {ironfurnaces@1.9.0 DONE}
		simplylight-1.15.2-0.9.0.jar Simply Light {simplylight@1.15.2-0.9.0 DONE}
		simplefarming-1.15.1-1.2.7.jar Simple Farming {simplefarming@1.15.1-1.2.7 DONE}
		RaysDongles-4.2.2b.jar Ray's Dongles {slurpiesdongles@4.2.2b DONE}
		tgcropesmod-1.15.2-1.1.1.jar Ropes Mod {tgcropesmod@1.15.2-1.1.1 DONE}
		randomenchants-3.1.0.jar Random Enchants {randomenchants@3.1.0 DONE}
		curios-FORGE-1.15.2-2.0-beta2.jar Curios API {curios@FORGE-1.15.2-2.0-beta2 DONE}
		corail_woodcutter-1.1.1-1.15.2.jar Corail Woodcutter {corail_woodcutter@1.1.1 DONE}
		OverpoweredMending-1.15.2-2.0.0+11.jar Overpowered Mending {overpowered_mending@2.0.0+11 DONE}
		floradoubling-1.15.2-20w06a-1.0.0.jar Flora Doubling {floradoubling@1.15.2-20w06a-1.0.0 DONE}
		additionalevents-1.0a.jar Additional Events {additionalevents@1.0a DONE}
		SBM-Magic-Mirror-1.15.2-1.0.1.jar SBM-Magic-Mirror {sbmmagicmirror@1.15.2-1.0.1 DONE}
		expandedstorage-1.1.6+1.15.2.jar Expanded Storage {expandedstorage@1.1.6+1.15.2 DONE}
		worldedit-forge-mc1.15.2-7.1.0.jar WorldEdit {worldedit@7.1.0;48cc31c DONE}
		mcw-roofs-1.0.2-mc1.15.2_1.15.1.jar Macaw's Roofs {mcwroofs@1.0.2 DONE}
		curiouselytra-FORGE-1.15.2-2.0.jar Curious Elytra {curiouselytra@FORGE-1.15.2-2.0 DONE}
		mcw-furnitures-1.0.0-mc1.15.2.jar Macaw's Furniture {mcwfurnitures@1.0.0 DONE}
		globalxp-1.15.2-v1.4.11.jar Global XP {globalxp@v1.4.11 DONE}
		betterwithminecolonies-1.15.2-1.13.14.jar Better With Minecolonies {betterwithminecolonies@1.15.2-1.13.14 DONE}
		Zmod+1.15.2-1.04.jar ZmodSkills {zmod@1.04 DONE}
		tramplestopper-1.15.2-2.0.0.5-universal.jar Trample Stopper {tramplestopper@1.15.2-2.0.0.5-universal DONE}
		speedyladders-1.15.2-1.jar Speedy Ladders {speedyladders@1.15.2-1 DONE}
		FastLeafDecay-v20.jar FastLeafDecay {fastleafdecay@v20 DONE}
		Cyclic-1.15.2-0.1.8.jar Cyclic {cyclic@1.15.2-0.1.8 DONE}
		cullparticles-1.0.jar Cull Particles {cullparticles@1.0 DONE}
		Ma-Enchants-1.15.2-3.0.0.jar Ma Enchants {ma-enchants@1.15.2-3.0.0 DONE}
		Cucumber-1.15.2-3.0.1.jar Cucumber Library {cucumber@3.0.1 DONE}
		torchslabmod-1.15.1_v1.5.jar Torch Slab Mod {torchslabmod@1.5.0 DONE}
		mining-helmet-1.15.2-1.0.6.jar Mining Helmet {mining_helmet@1.0.6 DONE}
		janoeo-3.1.2.jar Just Another Nether/Overworld/End Ores {janoeo@3.1.2 DONE}
		jei-1.15.2-6.0.0.2.jar Just Enough Items {jei@6.0.0.2 DONE}
		vanillathings-1.15.2-0.4.5.jar Vanilla Things {vanillathings@0.4.5 DONE}
		caelus-FORGE-1.15.2-2.0-beta1.jar Caelus API {caelus@FORGE-1.15.2-2.0-beta1 DONE}
		colytra-FORGE-1.15.2-3.0.jar Colytra {colytra@FORGE-1.15.2-3.0 DONE}
		invtweaks-1.15.2-1.0.0.jar Inventory Tweaks Reborn {invtweaks@1.15.2-1.0.0 DONE}
		Waystones_1.15.2-6.0.0.jar Waystones {waystones@6.0.0 DONE}
		MoreOresInONE-1.1_1.15.2.jar More Ores in ONE {moreoresinone@1.1 DONE}
		AutoDropper-1.14.3-5.0.0.jar Auto Dropper {autodropper@1.14.3-5.0.0 DONE}
		OresAboveDiamonds+1.15+v3.0.jar Ores Above Diamonds {oresabovediamonds@3.0 DONE}
		FruitTrees-1.15.2-1.1.5.jar Fruit Trees {fruittrees@1.1.5 DONE}
		Kiwi-1.15.2-2.6.5.jar Kiwi {kiwi@2.6.5 DONE}
		additionalbars-1.1.2.jar Additional Bars {additionalbars@1.1.2 DONE}
		SereneSeasons-1.15.2-3.0.0.57-universal.jar Serene Seasons {sereneseasons@1.15.2-3.0.0.57 DONE}
		VanillaTweaks-1.15.2.1.5.17.jar VanillaTweaks {vanillatweaks@1.15.2.1.5.17 DONE}
		DungeonCrawl-1.15.2-1.6.2.jar Dungeon Crawl {dungeoncrawl@1.6.2 DONE}
		RingOfTeleport-1.15.2-1.1.13.jar Ring of Teleport {ring_of_teleport@1.1.13 DONE}
		immersive-portals-0.4(for+mc+1.15+with+forge).jar Immersive Portals {immersive_portals@0.4 DONE}
		CraftTweaker-1.15.1-6.0.0.3.jar CraftTweaker {crafttweaker@6.0.0.3 DONE}
		forge-1.15.2-31.1.1-universal.jar Forge {forge@31.1.1 DONE}
		extradiscs-1.0.0-forge1.15.2+build.1.jar ExtraDiscs {extradiscs@1.0.0-forge1.15.2+build.1 DONE}
		forge-1.15.2-31.1.1-server.jar Minecraft {minecraft@1.15.2 DONE}
		cofh_core-1.15.2-0.3.1b.jar CoFH Core {cofh_core@0.3.1b DONE}
		ensorcellation-1.15.2-0.3.0b.jar Ensorcellation {ensorcellation@0.3.0b DONE}
		logprot-1.15.1-1.2.jar Logprot {logprot@1.2 DONE}
		woolplates-1.15.1-v1.2.1.jar Wool Pressure Plates {woolplates@v1.2.1 DONE}
		playerplates-1.15-forge-1.0.0.jar Player Plates {playerplates@1.15-forge-1.0.0 DONE}
		EasySteel-1.15.2-1.1.36.jar Easy Steel & More {easy_steel@1.1.36 DONE}
		instahouses-1.15.2-1.1.1.jar Slashkings InstaHouses {instahouses@1.1 DONE}
		useful_railroads-1.15.2-1.3.1.20.jar Useful Railroads {usefulrailroads@1.3.1.20 DONE}
		UndergroundMaterials-1.15.x-1.3.2.jar Underground Materials {undermat@1.3.2 DONE}
		woolbuttons-1.15.1-v1.1.jar Wool Buttons {sbmwoolbuttons@v1.1 DONE}
		theplopper-1.15.1-v1.3.jar The Plopper {theplopper@v1.3 DONE}
		archers_paradox-1.15.2-0.3.0b.jar Archer's Paradox {archers_paradox@0.3.0b DONE}
		extragolems-10.0.0-beta.jar Extra Golems {golems@10.0.0-beta DONE}
		dimdungeons-1.03-forge-1.15.2.jar Dimensional Dungeons {dimdungeons@1.14.4-1.03 DONE}
		HunterMod-1.15.2-1.0.2.jar Hunter Mod {huntermod@1.0.2 DONE}
		Xaeros_Minimap_20.3.0_Forge_1.15.2.jar Xaero's Minimap {xaerominimap@20.3.0 DONE}
		lava-monster-1.15.2-1.0.0.jar Lava Monster {lava_monster@1.0.0 DONE}
		corail_recycler-4.0.2-1.15.2.jar Corail Recycler {corail_recycler@4.0.2 DONE}
		DoubleSlabs-1.15-2.0.1.jar Double Slabs {doubleslabs@2.0.1 DONE}
		vanillahammers-1.15.1-1.0.jar Vanilla Hammers {vanillahammers@1.15.1-1.0 DONE}
		structurize-0.10.223-ALPHA.jar Structurize {structurize@0.10.223-ALPHA DONE}
		PickleTweaks-1.15.2-4.0.0.jar Pickle Tweaks {pickletweaks@4.0.0 DONE}
		minecolonies-0.10.678-RELEASE-universal.jar Minecolonies {minecolonies@0.10.678-RELEASE DONE}
		ruby-1.15.2.jar Just Another Ruby Mod {ruby@version DONE}
		Aquaculture-1.15.2-2.0.8.jar Aquaculture 2 {aquaculture@1.15.2-2.0.8 DONE}
		betterbedrockgenerator-1.15.2-0.0.6.jar Better Bedrock Generator {betterbedrockgenerator@0.0.6 DONE}
		parachutemod-1.15.1-2.3.1-463.jar Parachute Mod NG {parachutemod@1.15.1-2.3.1-463 DONE}
		lootbagmod-1.15.1-1.3.jar Loot Bag Mod {lootbagmod@1.15.1-1.3 DONE}
		draw_bridge-1.15.2-1.4.2.17.jar Draw Bridge {drawbridge@1.4.2.17 DONE}
	Kiwi Modules: 
		fruittrees:fruittrees
		fruittrees:hybridization
		kiwi:contributors
		snowrealmagic:snowrealmagic
	Player Count: 1 / 20; [ServerPlayerEntity['LordBaane'/253, l='world', x=-86.98, y=68.00, z=216.56]]
	Data Packs: vanilla, mod:additionalbars, mod:additionalevents (incompatible), mod:aquaculture, mod:archers_paradox (incompatible), mod:autodropper (incompatible), mod:bambooeverything (incompatible), mod:betterbedrockgenerator, mod:betterwithminecolonies (incompatible), mod:bowinfinityfix (incompatible), mod:caelus (incompatible), mod:carpetstairsmod, mod:cofh_core (incompatible), mod:colytra (incompatible), mod:corail_recycler, mod:corail_woodcutter, mod:corpse, mod:crafttweaker (incompatible), mod:cucumber, mod:cullparticles (incompatible), mod:curios (incompatible), mod:curiouselytra (incompatible), mod:cyclic (incompatible), mod:dimdungeons, mod:doubleslabs, mod:drawbridge, mod:dungeoncrawl (incompatible), mod:easy_steel (incompatible), mod:edit_sign (incompatible), mod:ensorcellation (incompatible), mod:essentialfeatures (incompatible), mod:expandedstorage (incompatible), mod:extradiscs (incompatible), mod:fastleafdecay, mod:floradoubling, mod:forge (incompatible), mod:fruittrees, mod:globalxp (incompatible), mod:golems (incompatible), mod:guardvillagers (incompatible), mod:huntermod, mod:immersive_portals (incompatible), mod:instahouses (incompatible), mod:invtweaks (incompatible), mod:ironfurnaces (incompatible), mod:janoeo (incompatible), mod:jei (incompatible), mod:jrftl (incompatible), mod:kiwi, mod:lava_monster (incompatible), mod:lightestlamp, mod:logprot (incompatible), mod:lootbagmod (incompatible), mod:ma-enchants (incompatible), mod:mcwbridges, mod:mcwfurnitures, mod:mcwroofs, mod:minecolonies (incompatible), mod:mining_helmet (incompatible), mod:moreoresinone (incompatible), mod:netherportalfix (incompatible), mod:oresabovediamonds (incompatible), mod:overpowered_mending (incompatible), mod:parachutemod, mod:pickletweaks, mod:placebo (incompatible), mod:playerplates (incompatible), mod:potionsmaster (incompatible), mod:prefab, mod:randomenchants (incompatible), mod:rhodonite, mod:ring_of_teleport (incompatible), mod:ruby (incompatible), mod:sbmmagicmirror (incompatible), mod:sbmwoolbuttons (incompatible), mod:sereneseasons, mod:simplefarming, mod:simplylight (incompatible), mod:slurpiesdongles, mod:snowrealmagic, mod:speedyladders, mod:structurize (incompatible), mod:tgcropesmod, mod:theplopper (incompatible), mod:torchslabmod, mod:tramplestopper (incompatible), mod:undermat (incompatible), mod:usefulbackpacks, mod:usefulrailroads, mod:uteamcore, mod:valhelsia_structures (incompatible), mod:vanillahammers, mod:vanillathings, mod:vanillatweaks, mod:waila (incompatible), mod:waystones (incompatible), mod:woolplates (incompatible), mod:worldedit (incompatible), mod:wstweaks (incompatible), mod:xaerominimap, mod:xaeroworldmap, mod:zmod
	Is Modded: Definitely; Server brand changed to 'forge'
	Type: Dedicated Server (map_server.txt)

**Comment by Lordbaane** [comment]
Posted on both mods to be sure.

**Comment by Lordbaane** [comment]
removed FLD and it stopped

**Comment by EnterFor** [comment]
The author seems to have disappeared recently, and I'm waiting to fix the problem

**Comment by sweiland** [comment]
Same issue here, let's hope it gets resolved eventually.

**Comment by Excaliburning** [comment]
This issue still happen with both mods, latest builds as of today.

**Comment by demonJ5** [comment]
Newest version of Fast Leaf Decay fixes this
https://www.curseforge.com/minecraft/mc-mods/fast-leaf-decay/files

**Comment by Excaliburning** [comment]
I confirm the issue is solved by the new build !
Thanks a lot !
