### ISSUE TITLE
Server crash from fruit leaves

### ISSUE THREAD

**Issue by yuhshii** [enemeez/simplefarming#65]
**Forge Version**

**Mod list (optional)**

**Log file (optional)**
---- Minecraft Crash Report ----
// You're mean.

Time: 2/22/20 5:46 AM
Description: Exception in server tick loop

java.lang.ClassCastException: enemeez.simplefarming.block.growable.FruitLeavesBlock cannot be cast to net.minecraft.block.LeavesBlock
	at net.olafkeijsers.fastleafdecay.FldScheduler.tick(FldScheduler.java:55) ~[?:v20] {re:classloading}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:212) ~[eventbus-2.0.0-milestone.1-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:204) ~[eventbus-2.0.0-milestone.1-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-2.0.0-milestone.1-service.jar:?] {}
	at net.minecraftforge.fml.hooks.BasicEventHooks.onPostServerTick(BasicEventHooks.java:119) ~[?:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:823) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:635) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_241] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_241, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1193559600 bytes (1138 MB) / 2304770048 bytes (2198 MB) up to 3817865216 bytes (3641 MB)
	CPUs: 6
	JVM Flags: 2 total; -Xmx4096M -Xms2048M
	ModLauncher: 5.0.0-milestone.4+67+b1a340b
	ModLauncher launch target: fmlserver
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-2.0.0-milestone.1-service.jar eventbus PLUGINSERVICE 
		/forgeserver.jar object_holder_definalize PLUGINSERVICE 
		/forgeserver.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.0.0-milestone.1-shadowed.jar accesstransformer PLUGINSERVICE 
		/forgeserver.jar capability_inject_definalize PLUGINSERVICE 
		/forgeserver.jar runtimedistcleaner PLUGINSERVICE 
		/forgeserver.jar fml TRANSFORMATIONSERVICE 
	FML: 31.1
	Forge: net.minecraftforge:31.1.0
	FML Language Providers: 
		javafml@31.1
		minecraft@1
	Mod List: 
		forge-1.15.2-31.1.0-server.jar Minecraft {minecraft@1.15.2 DONE}
		torchmaster-2.1.1-rc0.jar Torchmaster {torchmaster@2.1.1-rc0 DONE}
		inventorysorter-1.15.2-17.0.0.jar Simple Inventory Sorter {inventorysorter@17.0.0 DONE}
		colorfularmor-1.15.2-1.0.jar Colorful Armor {colorfularmor@1.0 DONE}
		glasscutter-1.0.0-mc1.15.2.jar Glasscutter {glasscutter@1.0.0 DONE}
		AmbientSounds_v3.0.16_mc1.15.2.jar Ambient Sounds {ambientsounds@3.0.3 DONE}
		torchslabmod-1.15.1_v1.5.jar Torch Slab Mod {torchslabmod@1.5.0 DONE}
		BiomesOPlenty-1.15.2-10.0.0.338-universal.jar Biomes O' Plenty {biomesoplenty@1.15.2-10.0.0.338 DONE}
		jei-1.15.2-6.0.0.2.jar Just Enough Items {jei@6.0.0.2 DONE}
		simplefarming-1.15.2-1.2.7.jar Simple Farming {simplefarming@1.15.2-1.2.7 DONE}
		FallingTree-1.15.2-2.0.3+19.jar Falling Tree {falling_tree@2.0.3+19 DONE}
		goblintraders-1.1.0-mc1.15.2.jar Goblin Traders {goblintraders@1.1.0 DONE}
		simplybackpacks-1.15.2-1.3.0.jar Simply Backpacks {simplybackpacks@1.15.2-1.3.0 DONE}
		findme-1.15.1-1.2.0.jar Find Me {findme@NONE DONE}
		Xaeros_Minimap_20.3.1.1_Forge_1.15.2.jar Xaero's Minimap {xaerominimap@20.3.1 DONE}
		Waystones_1.15.2-6.0.0.jar Waystones {waystones@6.0.0 DONE}
		ForgeEndertech-1.15.2-6.0.0.0-build.0004.jar Forge Endertech {forgeendertech@6.0.0.0 DONE}
		AdLods-1.15.2-3.0.0.0-build.0004.jar Large Ore Deposits {adlods@3.0.0.0 DONE}
		rndbmflowers_1.15-1.0.jar Random Bone Meal Flowers {rndbmflowers@1.0 DONE}
		gravestone-1.17.2.jar Gravestone Mod {gravestone@1.17.2 DONE}
		NaturesCompass-1.15.2-1.8.4.jar Nature's Compass {naturescompass@1.15.2-1.8.4 DONE}
		SereneSeasons-1.15.2-3.0.0.65-universal.jar Serene Seasons {sereneseasons@1.15.2-3.0.0.65 DONE}
		elevatorid-1.15.2-1.7.0.jar Elevator Mod {elevatorid@1.15.2-1.7.0 DONE}
		LightingWand-1.15.2-1.4.2.jar Lighting Wand {lightingwand@1.4.2 DONE}
		furniture-7.0.0-pre16-1.15.1.jar MrCrayfish's Furniture Mod {cfm@7.0.0-pre16 DONE}
		AppleSkin-mc1.15.2-forge-1.0.13.jar AppleSkin {appleskin@1.0.13 DONE}
		Hwyla-forge-1.10.8-B72_1.15.2.jar Waila {waila@version DONE}
		SnowRealMagic-1.15.2-1.7.2.jar Snow! Real Magic! {snowrealmagic@1.7.2 DONE}
		Kiwi-1.15.2-2.6.5.jar Kiwi {kiwi@2.6.5 DONE}
		CHAS+v1.3+for+1.15.jar Craftable Horse Armour {craftablehorsearmour@1.3 DONE}
		forge-1.15.2-31.1.0-universal.jar Forge {forge@31.1.0 DONE}
		FastLeafDecay-v20.jar FastLeafDecay {fastleafdecay@v20 DONE}
		supertools-1.15.2-1.0.jar Vanilla+ Tools {supertools@version DONE}
	Kiwi Modules: 
		kiwi:contributors
		snowrealmagic:snowrealmagic
	Player Count: 1 / 8; [ServerPlayerEntity['Yuhshii'/129, l='world', x=914.63, y=67.18, z=-780.90]]
	Data Packs: vanilla, mod:adlods (incompatible), mod:ambientsounds (incompatible), mod:appleskin (incompatible), mod:biomesoplenty, mod:cfm (incompatible), mod:craftablehorsearmour (incompatible), mod:falling_tree, mod:findme (incompatible), mod:forge (incompatible), mod:forgeendertech (incompatible), mod:gravestone, mod:inventorysorter (incompatible), mod:jei (incompatible), mod:kiwi, mod:lightingwand, mod:naturescompass (incompatible), mod:rndbmflowers (incompatible), mod:sereneseasons, mod:simplefarming, mod:simplybackpacks (incompatible), mod:snowrealmagic, mod:torchmaster (incompatible), mod:torchslabmod, mod:waystones (incompatible), mod:colorfularmor (incompatible), mod:elevatorid, mod:fastleafdecay, mod:glasscutter, mod:goblintraders, mod:supertools (incompatible), mod:waila (incompatible), mod:xaerominimap
	Is Modded: Definitely; Server brand changed to 'forge'
	Type: Dedicated Server (map_server.txt)
**Describe the issue**
Server crash randomly, I was not messing with fruit leaves at the time

**Comment by yuhshii** [comment]
idk what caused the error the first time, but I just tried to set one of the fruit trees on fire and now I get the crash every time I start the server

**Comment by enemeez** [comment]
If you are using a fast leaf decay mod, it is likely an incompatibility between our mods. I'll have this fixed soon.

**Comment by yuhshii** [comment]
I do not have fast leaf decay

**Comment by Nijoma69** [comment]
@yuhshii ... yes you do, check your mod list its listed in your crash logs above.
@enemeez ... I also have FastLeafDecay and I'm getting same error after sleeping (not even found a fruit tree yet)

---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 28/02/20 23:08
Description: Exception in server tick loop

java.lang.ClassCastException: enemeez.simplefarming.block.growable.FruitLeavesBlock cannot be cast to net.minecraft.block.LeavesBlock
	at net.olafkeijsers.fastleafdecay.FldScheduler.tick(FldScheduler.java:55) ~[?:v20] {re:classloading}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:212) ~[eventbus-2.0.0-milestone.1-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:204) ~[eventbus-2.0.0-milestone.1-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-2.0.0-milestone.1-service.jar:?] {}
	at net.minecraftforge.fml.hooks.BasicEventHooks.onPostServerTick(BasicEventHooks.java:119) ~[?:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:823) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:assets/immersive_portals/immersive_portals.mixins.json:MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:114) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:635) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:assets/immersive_portals/immersive_portals.mixins.json:MixinMinecraftServer,pl:mixin:A}
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_192] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_192, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 4315724632 bytes (4115 MB) / 6442450944 bytes (6144 MB) up to 6442450944 bytes (6144 MB)
	CPUs: 4
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 5.0.0-milestone.4+67+b1a340b
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-2.0.0-milestone.1-service.jar eventbus PLUGINSERVICE 
		/forge-1.15.2-31.1.16.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.15.2-31.1.16.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.0.3-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.15.2-31.1.16.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.15.2-31.1.16.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.15.2-31.1.16.jar fml TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.1.jar mixinbootstrap TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.1.jar mixin PLUGINSERVICE 
		/MixinBootstrap-1.0.1.jar mixinbootstrap PLUGINSERVICE 
	FML: 31.1
	Forge: net.minecraftforge:31.1.16
	FML Language Providers: 
		javafml@31.1
		minecraft@1
	Mod List: 
		inventorysorter-1.15.2-17.0.0.jar Simple Inventory Sorter {inventorysorter@17.0.0 DONE}
		compact-3.0.jar Compact {compact@3.0 DONE}
		ditr15-1.8.1.jar Diamond in the Rough {ditr15@1.8.1 DONE}
		Cucumber-1.15.2-3.0.1.jar Cucumber Library {cucumber@3.0.1 DONE}
		NetherPortalFix_1.15.2-6.0.0.jar NetherPortalFix {netherportalfix@6.0.0 DONE}
		craftingstation-3.0.5.jar Crafting Station {craftingstation@3.0.5 DONE}
		snad-1.8.4.22a-1.15.2.jar Snad {snad@1.8.3.3a DONE}
		jei-1.15.2-6.0.0.2.jar Just Enough Items {jei@6.0.0.2 DONE}
		longfallboots-1.4.0b.jar Long Fall Boots {longfallboots@1.4.0b DONE}
		goblintraders-1.1.1-1.15.2.jar Goblin Traders {goblintraders@1.1.1 DONE}
		planttech2-0.01.07.jar PlantTech 2 {planttech2@0.01.07 DONE}
		Mekanism-1.15.2-9.9.11.403.jar Mekanism {mekanism@9.9.11 DONE}
		mcw-windows-1.0.0-mc1.15.1_1.15.2.jar Macaw's Windows {mcwwindows@1.0.0 DONE}
		reap-1.12.1.jar Reap Mod {reap@1.12.1 DONE}
		KleeSlabs_1.15.2-8.0.0.jar KleeSlabs {kleeslabs@8.0.0 DONE}
		IronJetpacks-1.15.2-3.0.0.jar Iron Jetpacks {ironjetpacks@3.0.0 DONE}
		Waystones_1.15.2-6.0.0.jar Waystones {waystones@6.0.0 DONE}
		ForgeEndertech-1.15.2-6.0.0.0-build.0004.jar Forge Endertech {forgeendertech@6.0.0.0 DONE}
		XaerosWorldMap_1.5.5_Forge_1.15.2.jar Xaero's World Map {xaeroworldmap@1.5.5 DONE}
		ResourcefulTools-1.15.2-1.1.18.jar Resourceful Tools {resourceful_tools@1.1.18 DONE}
		OresAboveDiamonds+1.15+v3.1.1.jar Ores Above Diamonds {oresabovediamonds@3.0 DONE}
		dankstorage-2.5.jar Dank Storage {dankstorage@2.5 DONE}
		NoFog-1.15b1.jar NoFog {nofog@1.0.1 DONE}
		FruitTrees-1.15.2-1.1.6.jar Fruit Trees {fruittrees@1.1.6 DONE}
		Kiwi-1.15.2-2.6.5.jar Kiwi {kiwi@2.6.5 DONE}
		SereneSeasons-1.15.2-3.0.0.66-universal.jar Serene Seasons {sereneseasons@1.15.2-3.0.0.65 DONE}
		cursedearth-2.1.jar Cursed Earth {cursedearth@2.1 DONE}
		DungeonCrawl-1.15.2-1.6.3.jar Dungeon Crawl {dungeoncrawl@1.6.3 DONE}
		TheVeggieWay-1.15.2-2.1.19.jar The Veggie Way {veggie_way@2.1.19 DONE}
		u_team_core-1.15.2-2.10.6.155.jar U Team Core {uteamcore@2.10.6.155 DONE}
		mcjtylib-1.15-4.0.2-alpha.jar McJtyLib {mcjtylib@1.15-4.0.2-alpha DONE}
		rftoolsbase-1.15-1.0.0-alpha.jar RFToolsBase {rftoolsbase@1.15-1.0.0-alpha DONE}
		xnet-1.15-2.0.1-alpha.jar XNet {xnet@1.15-2.0.1-alpha DONE}
		travellersboots-1.15.2-1.3.2.jar Traveller's Boots {travellersboots@1.3.1 DONE}
		MekanismGenerators-1.15.2-9.9.11.403.jar Mekanism: Generators {mekanismgenerators@9.9.11 DONE}
		WaterStrainer-1.15.1-8.0.0.jar Water Strainer {waterstrainer@1.15.1-8.0.0 DONE}
		immersive-portals-0.4(for+mc+1.15+with+forge).jar Immersive Portals {immersive_portals@0.4 DONE}
		ExpOreMod-1.15.2-1.1.jar Exp Ore Block {exp_ore@1.1 DONE}
		rftoolspower-1.15-2.0.1-alpha.jar RFToolsPower {rftoolspower@1.15-2.0.1-alpha DONE}
		extradisks-1.15.1-1.2.jar Extra Disks {extradisks@1.15.1-1.2 DONE}
		forge-1.15.2-31.1.16-universal.jar Forge {forge@31.1.16 DONE}
		MysticalAgradditions-1.15.2-3.0.0.jar Mystical Agradditions {mysticalagradditions@3.0.0 DONE}
		refinedstorage-1.8.1.jar Refined Storage {refinedstorage@1.8.1 DONE}
		MysticalAgriculture-1.15.2-3.0.0.jar Mystical Agriculture {mysticalagriculture@3.0.0 DONE}
		CraftingTweaks_1.15.1-11.0.0.jar Crafting Tweaks {craftingtweaks@11.0.0 DONE}
		forge-1.15.2-31.1.16-client.jar Minecraft {minecraft@1.15.2 DONE}
		mcw-bridges-1.0.3-mc1.15.2.jar Macaw's Bridges {mcwbridges@1.0.3 DONE}
		industrial-foregoing-1.15.2-2.2.1-f27c515.jar Industrial Foregoing {industrialforegoing@2.2.1 DONE}
		rftoolsutility-1.15-2.0.0-alpha.jar RFToolsUtility {rftoolsutility@1.15-2.0.0-alpha DONE}
		useful_backpacks-1.15.2-1.9.4.63.jar Useful Backpacks {usefulbackpacks@1.9.4.63 DONE}
		theoneprobe-1.15-2.0.1.jar The One Probe {theoneprobe@1.15-2.0.1 DONE}
		titanium-1.15.2-2.3.6.jar Titanium {titanium@2.3.6 DONE}
		EasySteel-1.15.2-1.1.44.jar Easy Steel & More {easy_steel@1.1.44 DONE}
		BiomesOPlenty-1.15.2-10.0.0.345-universal.jar Biomes O' Plenty {biomesoplenty@1.15.2-10.0.0.342 DONE}
		Durability101-1.15-0.0.3.jar Durability101 {durability101@0.0.3 DONE}
		valkyrielib-1.15.2-3.0.2.0.jar ValkyrieLib {valkyrielib@1.15.2-3.0.2.0 DONE}
		simplechunkloaders-1.15.2-1.0.2.0.jar Simple Chunk Loaders {simplechunkloaders@NONE DONE}
		AdLods-1.15.2-3.0.0.0-build.0004.jar Large Ore Deposits {adlods@3.0.0.0 DONE}
		simplefarming-1.15.2-1.2.7.jar Simple Farming {simplefarming@1.15.2-1.2.7 DONE}
		rftoolsbuilder-1.15-2.0.0-alpha.jar RFToolsBuilder {rftoolsbuilder@1.15-2.0.0-alpha DONE}
		SolarFluxReborn-1.15.2-15.0.0.jar Solar Flux Reborn {solarflux@15.0.0 DONE}
		curios-FORGE-1.15.2-2.0.jar Curios API {curios@FORGE-1.15.2-2.0 DONE}
		Xaeros_Minimap_20.3.1.1_Forge_1.15.2.jar Xaero's Minimap {xaerominimap@20.3.1 DONE}
		rftoolsstorage-1.15-1.0.2-alpha.jar RFToolsStorage {rftoolsstorage@1.15-1.0.2-alpha DONE}
		gravestone-1.17.3.jar Gravestone Mod {gravestone@1.17.3 DONE}
		corail_recycler-4.0.2-1.15.2.jar Corail Recycler {corail_recycler@4.0.2 DONE}
		StorageDrawers-1.15.2-7.0.2.jar Storage Drawers {storagedrawers@1.15.2-7.0.1 DONE}
		OreExcavation-1.7.149.jar Ore Excavation {oreexcavation@NONE DONE}
		nether_ores-1.1.jar Nether ores {nether_ores@v1.1 DONE}
		angelring-1.15.2-1.2.0.jar Angel Ring {angelring@1.2.0 DONE}
		elevatorid-1.15.2-1.7.0.jar Elevator Mod {elevatorid@1.15.2-1.7.0 DONE}
		Gobber2-1.15.2-2.2.51.jar Gobber 2 {gobber2@2.2.51 DONE}
		PowderPower-1.15.2-3.1.37.jar Powder Power {powder_power@3.1.37 DONE}
		PickleTweaks-1.15.2-4.0.0.jar Pickle Tweaks {pickletweaks@4.0.0 DONE}
		MekanismTools-1.15.2-9.9.11.403.jar Mekanism: Tools {mekanismtools@9.9.11 DONE}
		mcw-roofs-1.0.2-mc1.15.2_1.15.1.jar Macaw's Roofs {mcwroofs@1.0.2 DONE}
		AppleSkin-mc1.15.2-forge-1.0.13.jar AppleSkin {appleskin@1.0.13 DONE}
		mobcatcher-2.2.jar Mob Catcher {mobcatcher@2.2 DONE}
		engineersdecor-1.15.2-1.0.19-b4.jar Engineer's Decor {engineersdecor@1.0.19-b4 DONE}
		mcw-furnitures-1.0.0-mc1.15.2.jar Macaw's Furniture {mcwfurnitures@1.0.0 DONE}
		globalxp-1.15.2-v1.4.11.jar Global XP {globalxp@v1.4.11 DONE}
		almostalltheores-2.0.1.3.jar Almost All the Ores {almostalltheores@2.0.1.3 DONE}
		Aquaculture-1.15.2-2.0.9.jar Aquaculture 2 {aquaculture@1.15.2-2.0.9 DONE}
		tramplestopper-1.15.2-2.0.0.4-universal.jar Trample Stopper {tramplestopper@1.15.2-2.0.0.4-universal DONE}
		betterbedrockgenerator-1.15.2-0.0.6.jar Better Bedrock Generator {betterbedrockgenerator@0.0.6 DONE}
		XL-Food-Mod-1.15.2-2.2.2.jar XL Food Mod {xlfoodmod@2.2.2 DONE}
		refinedstorageaddons-0.6.1.jar Refined Storage Addons {refinedstorageaddons@0.6.1 DONE}
		SolarGeneration-1.15.2-1.2.0.jar Solar Generation {solargeneration@1.2.0 DONE}
		FastLeafDecay-v20.jar FastLeafDecay {fastleafdecay@v20 DONE}
		Disenchanting_(forge)_1.15.2-1.2.0.jar Disenchanting {disenchanting@1.2.0 DONE}
		luckyores-1.15.2-1.3.1.jar Lucky Ores Mod {luckyores@1.3 DONE}
		Cyclic-1.15.2-0.1.10.jar Cyclic {cyclic@1.15.2-0.1.10 DONE}
		xptome-1.15.1-v1.1.4.jar XP Tome {xpbook@v1.1.4 DONE}
		bigbuckets-1.1.0.jar BigBuckets {bigbuckets@1.1.0 DONE}
	Kiwi Modules: 
		fruittrees:fruittrees
		fruittrees:hybridization
		kiwi:contributors
	Player Count: 1 / 8; [ServerPlayerEntity['Nijoma'/281, l='Lets Play', x=141.39, y=64.00, z=2.21]]
	Data Packs: vanilla, mod:adlods (incompatible), mod:almostalltheores, mod:angelring (incompatible), mod:appleskin (incompatible), mod:aquaculture, mod:betterbedrockgenerator, mod:bigbuckets (incompatible), mod:biomesoplenty, mod:compact (incompatible), mod:corail_recycler, mod:craftingstation (incompatible), mod:craftingtweaks (incompatible), mod:cucumber, mod:curios (incompatible), mod:cursedearth (incompatible), mod:cyclic (incompatible), mod:dankstorage (incompatible), mod:disenchanting (incompatible), mod:ditr15, mod:dungeoncrawl (incompatible), mod:durability101, mod:easy_steel (incompatible), mod:elevatorid, mod:engineersdecor, mod:exp_ore, mod:extradisks, mod:fastleafdecay, mod:forge (incompatible), mod:forgeendertech (incompatible), mod:fruittrees, mod:globalxp (incompatible), mod:gobber2 (incompatible), mod:goblintraders, mod:gravestone, mod:immersive_portals (incompatible), mod:industrialforegoing (incompatible), mod:inventorysorter (incompatible), mod:ironjetpacks, mod:jei (incompatible), mod:kiwi, mod:kleeslabs (incompatible), mod:longfallboots (incompatible), mod:luckyores (incompatible), mod:mcjtylib (incompatible), mod:mcwbridges, mod:mcwfurnitures, mod:mcwroofs, mod:mcwwindows, mod:mekanism, mod:mekanismgenerators, mod:mekanismtools, mod:mobcatcher (incompatible), mod:mysticalagradditions, mod:mysticalagriculture, mod:nether_ores, mod:netherportalfix (incompatible), mod:nofog (incompatible), mod:oreexcavation (incompatible), mod:oresabovediamonds (incompatible), mod:pickletweaks, mod:planttech2 (incompatible), mod:powder_power (incompatible), mod:reap, mod:refinedstorage (incompatible), mod:refinedstorageaddons (incompatible), mod:resourceful_tools (incompatible), mod:rftoolsbase (incompatible), mod:rftoolsbuilder (incompatible), mod:rftoolspower (incompatible), mod:rftoolsstorage (incompatible), mod:rftoolsutility (incompatible), mod:sereneseasons, mod:simplechunkloaders (incompatible), mod:simplefarming, mod:snad, mod:solarflux (incompatible), mod:solargeneration (incompatible), mod:storagedrawers (incompatible), mod:theoneprobe (incompatible), mod:titanium (incompatible), mod:tramplestopper (incompatible), mod:travellersboots (incompatible), mod:usefulbackpacks, mod:uteamcore, mod:valkyrielib (incompatible), mod:veggie_way (incompatible), mod:waterstrainer, mod:waystones (incompatible), mod:xaerominimap, mod:xaeroworldmap, mod:xlfoodmod, mod:xnet (incompatible), mod:xpbook (incompatible)
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'

**Comment by yuhshii** [comment]
Sorry I thought I took it out, I knew FLD caused problems so i took it out but i guess it ended up in there again somehow

**Comment by HellishINC** [comment]
I believe I have the same issue though my stack trace is slightly different from the original. Possibly due to different forge revisions. Yes, I'm running FastLeafDecay as well.

```
---- Minecraft Crash Report ----
// Don't do that.

Time: 3/10/20 6:46 PM
Description: Exception in server tick loop

java.lang.ClassCastException: enemeez.simplefarming.block.growable.FruitLeavesBlock cannot be cast to net.minecraft.block.LeavesBlock
	at net.olafkeijsers.fastleafdecay.FldScheduler.tick(FldScheduler.java:55) ~[?:v20] {re:classloading}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:212) ~[eventbus-2.0.0-milestone.1-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:204) ~[eventbus-2.0.0-milestone.1-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-2.0.0-milestone.1-service.jar:?] {}
	at net.minecraftforge.fml.hooks.BasicEventHooks.onPostServerTick(BasicEventHooks.java:119) ~[?:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:825) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:114) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:637) [?:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242] {}
```

**Comment by IchigoGames** [comment]
same crash as above https://pastebin.com/mL5CHJjU for 1.15 simplefarming-1.15.2-1.2.7.jar
