### ISSUE TITLE
java.lang.NullPointerException on loot table parser

### ISSUE THREAD

**Issue by dreckz** [enemeez/simplefarming#72]
**Forge Version**
31.1.19
**Mod list (optional)**

**Log file (optional)**
[latest.log](https://github.com/enemeez/simplefarming/files/4327902/latest.log)

**Describe the issue**
java.lang.NullPointerException found in the log on loot table parser.

**Comment by cech12** [comment]
Maybe it is a problem of another mod: https://github.com/TheGoldCrayon/RopesMod/issues/5

Can you deactivate the RopesMod and test if its working?
