### ISSUE TITLE
Brewing barrel not returning beer after right clicking. (Server)

### ISSUE THREAD

**Issue by Effectstudios** [enemeez/simplefarming#74]
**Forge Version**
31.1.25

**Mod list (optional)**
Ma-Enchants-1.15.2-3.0.0.jar Ma Enchants {ma-enchants@1.15.2-3.0.0 DONE}
		TrashSlot_1.15.2-11.0.0.jar TrashSlot {trashslot@11.0.0 DONE}
		mining-helmet-1.15.2-1.0.7.jar Mining Helmet {mining_helmet@1.0.7 DONE}
		craftingstation-3.0.5.jar Crafting Station {craftingstation@3.0.5 DONE}
		jei-1.15.2-6.0.0.2.jar Just Enough Items {jei@6.0.0.2 DONE}
		Buzzier-Bees-Mod-1.15.2.jar Buzzier Bees {buzzierbees@1.1.4 DONE}
		DoggyTalents-1.15.2-1.15.2.3.jar Doggy Talents {doggytalents@1.15.2.3 DONE}
		mcw-windows-1.0.0-mc1.15.1_1.15.2.jar Macaw's Windows {mcwwindows@1.0.0 DONE}
		caelus-FORGE-1.15.2-2.0-beta1.jar Caelus API {caelus@FORGE-1.15.2-2.0-beta1 DONE}
		colytra-FORGE-1.15.2-3.0.jar Colytra {colytra@FORGE-1.15.2-3.0 DONE}
		BowInfinityFix-1.15.2-rv8.jar Bow Infinity Fix {bowinfinityfix@rv8 DONE}
		Waystones_1.15.2-6.0.0.jar Waystones {waystones@6.0.0 DONE}
		ForgeEndertech-1.15.2-6.0.0.0-build.0004.jar Forge Endertech {forgeendertech@6.0.0.0 DONE}
		timber-1.15.2-1.4.jar Timber Mod {timber@1.4 DONE}
		CookingForBlockheads_1.15.2-8.0.0.jar Cooking for Blockheads {cookingforblockheads@8.0.0 DONE}
		Placebo-1.15.2-3.0.2.jar Placebo {placebo@3.0.2 DONE}
		Comforts-Mod-1.15.2.jar Comforts {comforts@FORGE-1.15.2-2.0 DONE}
		serversync-forge-loader-1.0.0.jar ServerSync Forge Loader {serversync-forge-loader@1.0.0 DONE}
		SereneSeasons-1.15.2-3.0.0.68-universal.jar Serene Seasons {sereneseasons@1.15.2-3.0.0.68 DONE}
		compactxpbottles-1.15.2-1.2.1.jar Compact Experience Bottles {compactxpbottles@1.1.2 DONE}
		decorative_blocks_6c.jar Decorative Blocks {decorative_blocks@1.6 DONE}
		VanillaTweaks-1.15.2.1.5.18.jar VanillaTweaks {vanillatweaks@1.15.2.1.5.18 DONE}
		WitherSkeletonTweaks-1.15.1-4.0.0.jar Wither Skeleton Tweaks {wstweaks@4.0.0 DONE}
		FarmingForBlockheads_1.15.2-6.1.0.jar Farming for Blockheads {farmingforblockheads@6.1.0 DONE}
		u_team_core-1.15.2-2.10.6.155.jar U Team Core {uteamcore@2.10.6.155 DONE}
		permasomnia_v1.1.1_formc1.15.2.jar Permasomnia {permasomnia@1.1.1 DONE}
		environmentalcreepers-forge-1.15.2-1.6.1.jar Environmental Creepers {environmentalcreepers@1.6.1 DONE}
		Hwyla-forge-1.10.8-B72_1.15.2.jar Waila {waila@version DONE}
		WaterStrainer-1.15.1-8.0.0.jar Water Strainer {waterstrainer@1.15.1-8.0.0 DONE}
		walljump-forge-1.15.2-1.3.5.jar Wall-Jump! {walljump@1.15.2-1.3.5 DONE}
		speedyhoppers-1.15.2-2.jar Speedy Hoppers {speedyhoppers@1.15.2-2 DONE}
		SnowRealMagic-1.15.2-1.7.2.jar Snow! Real Magic! {snowrealmagic@1.7.2 DONE}
		Kiwi-1.15.2-2.6.5.jar Kiwi {kiwi@2.6.5 DONE}
		FpsReducer-mc1.15.2-1.14.1.jar FPS Reducer {fpsreducer@mc1.15.2-1.14.1 DONE}
		BetterThanMending-1.4.0.jar BetterThanMending {betterthanmending@1.4.0 DONE}
		forge-1.15.2-31.1.25-universal.jar Forge {forge@31.1.25 DONE}
		mshrtw_1.15.2-1.0.jar Mooshroom Tweaks {mshrtw@1.0 DONE}
		Absent-by-Design-Mod-1.15.2.jar Absent By Design Mod {absentbydesign@1.15.2-1.0.5  DONE}
		exp_bottling-1.15.2-1.jar EXP Bottling {exp_bottling@1.15.2-1 DONE}
		anviltweaks-2.2a.jar Anvil Tweaks {anviltweaks@2.2a DONE}
		forge-1.15.2-31.1.25-server.jar Minecraft {minecraft@1.15.2 DONE}
		mcw-bridges-1.0.4fix-mc1.15.2.jar Macaw's Bridges {mcwbridges@1.0.4 DONE}
		luckyblock-1.15.2-1.jar Lucky Block {lucky@1.15.2-1 DONE}
		torchmaster-2.1.1-rc0.jar Torchmaster {torchmaster@2.1.1-rc0 DONE}
		EnchantmentDescriptions-1.15.2-2.0.3.jar EnchantmentDescriptions {enchdesc@2.0.3 DONE}
		AmbientSounds_v3.0.17_mc1.15.2.jar Ambient Sounds {ambientsounds@3.0.3 DONE}
		ToolBelt-1.15.2-1.14.1.jar Tool Belt {toolbelt@1.14.1 DONE}
		ExtraButtons-1.15.2-3.0.0.jar ExtraButtons {extrabuttons@1.15.2-3.0.0 DONE}
		AdLods-1.15.2-3.0.1.0-build.0008.jar Large Ore Deposits {adlods@3.0.1.0 DONE}
		SoulShardsRespawn-forge-1.15.2-1.2.0-15.jar Soul Shards Respawn {soulshards@version DONE}
		simplylight-1.15.2-0.9.0.jar Simply Light {simplylight@1.15.2-0.9.0 DONE}
		simplefarming-1.15.2-1.2.7.jar Simple Farming {simplefarming@1.15.2-1.2.7 DONE}
		astikorcarts-1.0.2-1.15.2.jar AstikorCarts {astikorcarts@1.0.2 DONE}
		Simply-Backpacks-Mod-1.15.2.jar Simply Backpacks {simplybackpacks@1.15.2-1.4.0 DONE}
		Bountiful-3.0.0-1.15.2.jar Bountiful {bountiful@3.0.0-1.15.2 DONE}
		dimdungeons-1.051-forge-1.15.2.jar Dimensional Dungeons {dimdungeons@1.15.2-1.05 DONE}
		carrotslib-mc1.15.2-2.5b1.jar Carrots Lib {carrots@2.5.0b1 DONE}
		vanillafoodpantry-mc1.15.2-5.5b1.jar Vanilla Food Pantry {vanillafoodpantry@5.5.0b1 DONE}
		FastWorkbench-1.15.1-3.0.0.jar FastWorkbench {fastbench@3.0.0 DONE}
		ClothConfig2-2.0.jar Cloth Config Forge v2 API {cloth-config2@2.0 DONE}
		StorageDrawers-1.15.2-7.0.2.jar Storage Drawers {storagedrawers@1.15.2-7.0.1 DONE}
		DoubleSlabs-1.15-2.0.1.jar Double Slabs {doubleslabs@2.0.1 DONE}
		betbeacpl_1.15.2-1.0 (1).jar Better Beacon Placement {betbeacpl@1.0 DONE}
		tombstone-4.2.5-1.15.2.jar Corail Tombstone {tombstone@4.2.5 DONE}
		Smoke-1.15.2-2.0.0.jar Smoke {smoke@2.0.0 DONE}
		FastFurnace-1.15.1-3.0.0.jar FastFurnace {fastfurnace@3.0.0 DONE}
		AppleSkin-mc1.15.2-forge-1.0.13.jar AppleSkin {appleskin@1.0.13 DONE}
		engineersdecor-1.15.2-1.0.20-b1.jar Engineer's Decor {engineersdecor@1.0.20-b1 DONE}
		AI-Improvements-1.15.2-0.3.0.jar AI-Improvements {aiimprovements@0.3.0 DONE}
		solcarrot-1.15.2-1.9.4.jar Spice of Life: Carrot Edition {solcarrot@1.15.2-1.9.4 DONE}
		netherpspr_1.15.2-2.1.jar Nether Portal Spread {netherpspr@2.1 DONE}
		easyelytrato_1.15-1.2.jar Easy Elytra Takeoff {easyelytrato@1.2 DONE}
		ilikewood-1.15.2-2.2.0.1.jar I Like Wood {ilikewood@1.15.2-2.2.0.1 DONE}
		Aquaculture-1.15.2-2.0.11.jar Aquaculture 2 {aquaculture@1.15.2-2.0.11 DONE}
		tramplestopper-1.15.2-2.0.0.5-universal.jar Trample Stopper {tramplestopper@1.15.2-2.0.0.5-universal DONE}
		BetterBurning-1.15.2-1.3.1.jar BetterBurning {betterburning@1.3.1 DONE}
		PrettyBeaches_1.15.1-4.0.0.jar Pretty Beaches {prettybeaches@4.0.0 DONE}
		Vanilla+-Tools-Mod-1.15.2.jar Vanilla+ Tools {supertools@version DONE}
**Log file (optional)**

**Describe the issue**
After letting barley ferment in the barrel and the particles have stopped, right clicking on the barrel with an empty bottle consume the bottle but does not return the beer. I have tried with the bottle in a stack of 64 and as a single bottle.

**Comment by Abbathor92** [comment]
I'm currently not playing in any server, only play alone. For what I've seen, the barrels only return the fermented result if I doesn't log out. If I put the barrels to work and I logout, when I login, don't return the result, but if I put the barrels to work and wait to finish without logout, it return the result.

**Comment by Abbathor92** [comment]
I correct myself, playing alone, the chunk were de barrels are located must be always loaded so they work normally. If the chunk is not loaded it is reason enough for the barrels not to return the result.
