### ISSUE TITLE
Config Question

### ISSUE THREAD

**Issue by TheUntamed** [enemeez/simplefarming#79]
> ["Tweak World Generation Rates"]
> 	#Chance of berry bushes generating in the overworld. **Higher numbers indicate a lower probability** (Default: 300)
> 	#Range: 1 ~ 1000000000

Why do higher numbers indicate a lower probability? That makes no sense to me. Or is that a typing error?

**Comment by enemeez** [comment]
It has to do with how the number is evaluated within the code. You can see an example [here](https://github.com/enemeez/simplefarming/blob/f792b33834dd43deee75687abc0d4d73d128ffff/src/main/java/enemeez/simplefarming/world/gen/BerryBushFeature.java#L38-L72).
