### ISSUE TITLE
Simple Farming seeds don't drop from grass.

### ISSUE THREAD

**Issue by SwanX1** [enemeez/simplefarming#82]
**Forge Version**
28.2.3 (1.14.4)
**Mod Version**
1.14.4-1.2.8

**Describe the issue**
No Simple Farming seeds drop from grass, only wheat seeds do. No warnings or errors in game console. [JEI Block Drops](https://www.curseforge.com/minecraft/mc-mods/block-drops-jei-addon) also show no other drops from grass.
![JEI Block Drops screenshot](https://i.imgur.com/Q5fzK50.png)
Help, will answer to any follow-up questions!

**Comment by cech12** [comment]
Do you have some other mods installed? My mod Ceramic Shears had the same issue in combination with other mods, that I fixed in my new release.

**Comment by SwanX1** [comment]
> Do you have some other mods installed? My mod Ceramic Shears had the same issue in combination with other mods, that I fixed in my new release.

Not any that could interfere with drops?
[Full mod list](https://pastebin.com/embed_iframe/YVM4PBQ6)

Hope this helps!

**Comment by cech12** [comment]
I'm not a developer of this mod here. 
Maybe the log file could be also helpful ;)

**Comment by SwanX1** [comment]
> Maybe the log file could be also helpful ;)
The log file shows nothing about this, I checked. No warnings, errors from the mod or loot table.

**Comment by cech12** [comment]
Than, I think, another mod is overriding the loot table. You can test if the mod alone works and enable/disable the other mods to find out which mod does the overriding.

**Comment by cech12** [comment]
I found the mod! The Simple Ores mod im 1.14 changes the loot tables because of its copper shears. Please deactivate this mod an test if it is working. Here is an issue of the mod where the problem is described: https://github.com/Sinhika/SimpleOres2/issues/19

**Comment by SwanX1** [comment]
> I found the mod! The Simple Ores mod im 1.14 changes the loot tables because of its copper shears.

OMG! Thank you so much! I was losing my mind trying to solve this!
