### ISSUE TITLE
2 block high plants growing 3 high when using bone meal and producing more than usual.

### ISSUE THREAD

**Issue by BrokenDoop** [enemeez/simplefarming#99]
1.16.1-forge-32.0.98
simplefarming-1.16.1-1.3.2.jar

I was going to explain every detail about this but it was honestly too confusing, I'll sum it up to "using bone meal on the top block of a two high tall plant will have odd behavior allowing the production of more plants than usual and duplicating blocks on top making it 3 high"

![unknown](https://user-images.githubusercontent.com/45373918/89495180-92f21580-d76c-11ea-9821-a551a1635aca.png)

**Comment by cweckerl** [comment]
I have this fixed, but I have not made a new update with the fix yet. Thanks for reporting this regardless.

**Comment by BrokenDoop** [comment]
> I have this fixed, but I have not made a new update with the fix yet. Thanks for reporting this regardless.

Ah, thank you.
